### ISSUE TITLE
MonitorManagementClient Import error

### ISSUE THREAD

**Issue by mad056** [nccgroup/ScoutSuite#861] opened 2020-09-20 12:56 UTC
Hi all,

Keep getting this error no matter how i try to authenticate with Azure. Not sure what the issue is here, have tried reinstalling and trying both pip/github install methods.

Error:  __main__.py L212: Initialization failure: cannot import name 'MonitorManagementClient' from 'azure.mgmt.monitor' (c:\scoutsuite-master\env\lib\site-packages\azure\mgmt\monitor\__init__.py)

**Comment by j4v** [comment] 2020-09-20 13:41
Please detail the exact installation steps.

**Comment by mad056** [comment] 2020-09-20 14:12
Thanks for the reply

1. I installed the Azure cli
2. Created a virtualized environment
'python -m venv env'
3. Activated the environment
'.env\Scripts\activate'
3. Installed Scoutsuite
'pip install scoutsuite'
4.Logged into azure within the vritualised environment 'az login'
5. Ran 'scout azure --cli'
and that produced the error message.
I also tried authentication with
'scout azure -tenant my_Id --user-account-browser'
That also produced the same error. I checked that the Azure monitor was
installed and it was....quite strange

Thanks for the help

**Comment by j4v** [comment] 2020-09-20 17:20
Can you run with `--debug` and paste the full output?

**Comment by mad056** [comment] 2020-09-21 01:14
Hi,

Please see the output below, hopefully I havent done anything silly or am
forgetting anything simple.


Traceback (most recent call last):
  File "c:\scoutsuite-master\env\lib\site-packages\ScoutSuite\__main__.py",
line 212, in _run
    cloud_provider = get_provider(provider=provider,
  File "c:\scoutsuite-master\env\lib\site-packages\ScoutSuite\providers\__init__.py",
line 36, in get_provider
    provider_object = get_provider_object(provider)
  File "c:\scoutsuite-master\env\lib\site-packages\ScoutSuite\providers\__init__.py",
line 10, in get_provider_object
    provider_module =
__import__('ScoutSuite.providers.{}.provider'.format(provider),
fromlist=[provider_class])
  File "c:\scoutsuite-master\env\lib\site-packages\ScoutSuite\providers\azure\provider.py",
line 6, in <module>
    from ScoutSuite.providers.azure.services import AzureServicesConfig
  File "c:\scoutsuite-master\env\lib\site-packages\ScoutSuite\providers\azure\services.py",
line 2, in <module>
    from ScoutSuite.providers.azure.facade.base import AzureFacade
  File "c:\scoutsuite-master\env\lib\site-packages\ScoutSuite\
providers\azure\facade\base.py", line 8, in <module>
    from ScoutSuite.providers.azure.facade.storageaccounts import
StorageAccountsFacade
  File "c:\scoutsuite-master\env\lib\site-packages\ScoutSuite\
providers\azure\facade\storageaccounts.py", line 3, in <module>
    from azure.mgmt.monitor import MonitorManagementClient
ImportError: cannot import name 'MonitorManagementClient' from
'azure.mgmt.monitor' (c:\scoutsuite-master\env\lib\site-packages\azure\mgmt\
monitor\__init__.py)

Thanks for the help

**Comment by thommor** [comment] 2020-09-21 06:47
@mad056 Could you confirm the version of Azure CLI you have installed as well as the version of azure-mgmt-monitor that was installed by pip please.

**Comment by j4v** [comment] 2020-09-21 07:11
> as well as the version of azure-mgmt-monitor that was installed by pip

Good eye~

I've reproduced this issue with the latest version of `azure-mgmt-monitor`, will resolve in `develop` today.

**Comment by j4v** [comment] 2020-09-21 08:12
This has been fixed in `develop` via https://github.com/nccgroup/ScoutSuite/pull/864. See https://github.com/nccgroup/ScoutSuite/issues/862 for long-term fix.

**Closed by j4v** 2020-09-21 08:12 UTC
Labels: bug, component-provider-azure

**Comment by i0na-k** [comment] 2020-09-28 16:11
Has this now been resolved?

**Comment by j4v** [comment] 2020-09-28 18:20
The issue is resolved in the `develop` branch and will be included in the 5.10 release which should come out this week.
