### ISSUE TITLE
Not able to run with -p profile flag set

### ISSUE THREAD

**Issue by klauern** [nccgroup/ScoutSuite#767] opened 2020-06-03 19:42 UTC
I am unable to run Scout from source unless I manually edit my `~/.aws/credentials` file to include a region.  By default, it does not:

![CleanShot 2020-06-03 at 14 35 44@2x](https://user-images.githubusercontent.com/4735/83681142-9835b700-a5a7-11ea-92a6-6dcce647e6b7.png)

```
$ AWS_PROFILE=sandbox1 python scout.py aws --services awslambda
2020-06-03 14:32:09 klauern scout[11679] INFO Launching Scout
2020-06-03 14:32:09 klauern scout[11679] INFO Authenticating to cloud provider
2020-06-03 14:32:10 klauern scout[11679] ERROR __main__.py L184: Authentication failure: Invalid endpoint: https://sts..amazonaws.com

$ AWS_PROFILE=sandbox1 AWS_REGION=us-west-2 python scout.py aws --services awslambda
2020-06-03 14:32:25 klauern scout[13148] INFO Launching Scout
2020-06-03 14:32:25 klauern scout[13148] INFO Authenticating to cloud provider
2020-06-03 14:32:27 klauern scout[13148] ERROR __main__.py L184: Authentication failure: Invalid endpoint: https://sts..amazonaws.com

$ AWS_PROFILE=sandbox1 AWS_REGION=us-west-2 python scout.py aws -p sandbox1 --services awslambda
2020-06-03 14:32:46 klauern scout[14925] INFO Launching Scout
2020-06-03 14:32:46 klauern scout[14925] INFO Authenticating to cloud provider
2020-06-03 14:32:47 klauern scout[14925] ERROR __main__.py L184: Authentication failure: Invalid endpoint: https://sts..amazonaws.com

$ AWS_PROFILE=sandbox1 AWS_REGION=us-west-2 python scout.py aws -p sandbox1 -r us-west-2  --services awslambda
2020-06-03 14:33:11 klauern scout[18684] INFO Launching Scout
2020-06-03 14:33:11 klauern scout[18684] INFO Authenticating to cloud provider
2020-06-03 14:33:13 klauern scout[18684] ERROR __main__.py L184: Authentication failure: Invalid endpoint: https://sts..amazonaws.com
```

However, when I add `us-west-2` to the `region = ` section, it works just fine:

![CleanShot 2020-06-03 at 14 43 27@2x](https://user-images.githubusercontent.com/4735/83682028-ef885700-a5a8-11ea-8962-9a7588ca2f85.png)

**Comment by ramimac** [comment] 2020-06-05 22:36
I wasn't able to trivially reproduce this, but betting you hit an edge case with the "new" region handling. will investigate

**Comment by ramimac** [comment] 2020-06-06 00:22
Quick notes on my debugging:

1. Main passes through to https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/authentication_strategy.py
2. authentication_strategy.py builds a boto3 Session, and then passes it to https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/utils.py
3. get_caller_identity in util uses the session to create an sts client and calls get_caller_identity

STS is global (and we're not attempting to regionalize it), so really not understanding how `sts..amazonaws.com` ends up getting called.

Also, not clear why I can't reproduce

@j4v

**Comment by ramimac** [comment] 2020-06-07 17:33
Ah. Revisited this and reproduced. The issue comes if you explicitly set:
`region = ` in your ~/.aws/credentials (a blank region).

AFAI can see, this isn't an issue with scout. In fact, I don't believe this is a valid configuration for ~/.aws/credentials at all. 

There are a few things causing your issue.
1) You're explicitly setting `region = `
2) I _think_ the environment variable would overwrite this and work, however you need to use [AWS_DEFAULT_REGION, not AWS_REGION](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configuration)
3) The `-r` command line flag for scout hasn't come into play at this point, as this is just hitting an error setting up boto3.

The open question here is:
Should setting the -r flag superseded other AWS environment configuration. I'm of the opinion not, because there are just too many edge cases we'd have to reimplement and handle. Better to leave that to boto3.

**Comment by klauern** [comment] 2020-06-07 18:47
Hello @ramimac,

Appreciate the digging in on this.  I'm not sure where the region is being explicitly set.  We have AWS gated through SAML, so i use [saml2aws](https://github.com/Versent/saml2aws) to simplify logging in on the CLI.  I will have to see if this is set within that app, because I don't generally have to modify this at all.

For Point #2, I'll have to try it out again.  I might have mistaken the ENV var that needed to be set.

Regarding point #3, I've always been of the opinion that CLI flags override everything.  For instance, in Go, the [`viper` library load configuration settings in a specific order](https://github.com/spf13/viper#why-viper):

> Viper uses the following precedence order. Each item takes precedence over the item below it:
> * explicit call to Set (from within the library itself)
> * flag (passed-on command-line)
> * env
> * config
> * key/value store
> * default

So while this might create issues in Scout, I would assume explicitness in the CLI should override implicit assumptions elsewhere (environment variable settings, config files and locations, etc.)

**Comment by ramimac** [comment] 2020-06-07 19:27
Hi @klauern ,

Thanks for the response.

On 1 - to clarify, I'm assuming it's explicitly set, just because that is the only way I could reproduce. Could be some other conflating factor!

On 2 - LMK.

On 3 - I understand where you're coming from. If a region is set, I believe this is the only place it wouldn't be used - because STS is global, so we are just passing off to boto3. But in the case the region is set both on the cli and elsewhere in the env, boto3 will take the env configuration, which could be different. I believe we could easily modify Scout to pass along an explicit region to the boto3 construction, if one is set on the cli. Just not sure if we want to. For right now, this is such an edge case with an explicit blank region in the ENV but a correct one on the CLI, that I don't know that it's worth any complexity to accommodate - @j4v will have to make that call

**Comment by klauern** [comment] 2020-06-08 01:48
ok, so for 2.  Switching to `AWS_DEFAULT_REGION` and setting that bypasses the issue.

However, one thought did occur to me that seems odd about this.  In my `~/.aws/config` file, I do set a default region in the profile I use:

```ini
[default]
profile = dev
output = json
[profile sandbox1]
region = us-west-2
```

There were other entries, but they were setting different profiles' regions.

**Comment by j4v** [comment] 2020-06-08 07:14
> I believe we could easily modify Scout to pass along an explicit region to the boto3 construction, if one is set on the cli. Just not sure if we want to. 

We do not, we let boto3 handle authentication in its default implementation, which allows us to offset any issues relating to it. If we start changing this then we can't just point to the boto3 documentation.

**Comment by ramimac** [comment] 2020-06-08 13:20
@klauern boto3 checks `~/.aws/config` last, so likely this is just hitting and using the explicitly set blank region still. Glad to ENV var is working for you.

Closing this as wont-fix

**Closed by ramimac** 2020-06-08 13:20 UTC
Labels: bug, component-provider-aws, invalid, wontfix
