### ISSUE TITLE
Docker build broken on master still

### ISSUE THREAD

**Issue by JLLeitschuh** [nccgroup/ScoutSuite#905] opened 2020-10-16 20:21 UTC
**Describe the bug**

Following the wiki with the master branch is broken.

**To Reproduce**

```
> docker-compose up --build
Building ncc-scoutsuite

Traceback (most recent call last):
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 346, in ensure_image_exists
  File "compose/service.py", line 1147, in build
compose.service.BuildError: (<Service: ncc-scoutsuite>, {'message': 'Cannot locate specified Dockerfile: src/Dockerfile'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 78, in main
TypeError: can only concatenate str (not "dict") to str
[65106] Failed to execute script docker-compose
```

After applying the following diff:

```
diff --git a/docker/docker-compose.yaml b/docker/docker-compose.yaml
index 27c60d32..626e5c1b 100644
--- a/docker/docker-compose.yaml
+++ b/docker/docker-compose.yaml
@@ -7,7 +7,7 @@ services:
     env_file:
       - config/build.env
     build:
-      context: src
+      context: .
       dockerfile: src/Dockerfile
       args:
         - VCS_REF
```

```
docker-compose up --build
Building ncc-scoutsuite
Step 1/19 : FROM python:3.8
3.8: Pulling from library/python
e4c3d3e4f7b0: Pull complete
101c41d0463b: Pull complete
8275efcd805f: Pull complete
751620502a7a: Pull complete
0a5e725150a2: Pull complete
397dba5694db: Pull complete
b453803265bc: Pull complete
a49354af7e01: Pull complete
3eb2f327eb62: Pull complete
Digest: sha256:d1bd83c5f824664b70a9afd482860603582ee56902c2dd77c685a00b63697b2e
Status: Downloaded newer image for python:3.8
 ---> a52c041f5098
Step 2/19 : LABEL maintainer="Jason Ross <jason.ross@nccgroup.com>"
 ---> Running in ce650c6b22da
Removing intermediate container ce650c6b22da
 ---> 606316cb380b
Step 3/19 : ARG VCS_REF
 ---> Running in 99b14ea47bed
Removing intermediate container 99b14ea47bed
 ---> 62a188761a41
Step 4/19 : ARG VCS_URL
 ---> Running in b83966c2cf72
Removing intermediate container b83966c2cf72
 ---> 0646e37491a2
Step 5/19 : ARG VERSION
 ---> Running in 733d90518507
Removing intermediate container 733d90518507
 ---> ea8f6058456c
Step 6/19 : ARG BUILD_DATE
 ---> Running in 2492bad70744
Removing intermediate container 2492bad70744
 ---> 517329c98ef3
Step 7/19 : ARG VENDOR
 ---> Running in a9e350c45c87
Removing intermediate container a9e350c45c87
 ---> 5520cad4db72
Step 8/19 : ARG NAME
 ---> Running in c888bcf80a7e
Removing intermediate container c888bcf80a7e
 ---> afddaf0fe560
Step 9/19 : ARG DESCRIPTION
 ---> Running in acfbb3992993
Removing intermediate container acfbb3992993
 ---> d7f43f9eb632
Step 10/19 : LABEL     org.label-schema.schema-version="1.0"     org.label-schema.build-date=$BUILD_DATE     org.label-schema.name=$NAME     org.label-schema.description=$DESCRIPTION     org.label-schema.vcs-ref=$VCS_REF     org.label-schema.vcs-url=$VCS_URL     org.label-schema.vendor=$VENDOR     org.label-schema.version=$VERSION
 ---> Running in 7ca280773840
Removing intermediate container 7ca280773840
 ---> be7807f04a9e
Step 11/19 : COPY bin /root/bin
ERROR: Service 'ncc-scoutsuite' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder073815497/bin: no such file or directory
```

**Additional context**

I'm running on MacOSX

**Comment by j4v** [comment] 2020-10-17 08:02
Looks like a duplicate of https://github.com/nccgroup/ScoutSuite/issues/882.

Should be fixed in https://github.com/nccgroup/ScoutSuite/pull/890, will be released next week. Appreciate if you can test.

**Closed by j4v** 2020-10-17 08:02 UTC
Labels: bug, potential

**Comment by JLLeitschuh** [comment] 2020-11-09 20:54
This is now working! 😄

**Comment by j4v** [comment] 2020-11-10 14:37
@JLLeitschuh  so... is this broken (https://github.com/nccgroup/ScoutSuite/issues/906#issuecomment-724272436) or not?

**Comment by JLLeitschuh** [comment] 2020-11-10 15:30
#906 is still broken; this issue #905 is fixed. The problems are distinct and different.
