### ISSUE TITLE
IAM Cross-account AssumeRole policy lacks external ID and MFA - Bug

### ISSUE THREAD

**Issue by jonnieb007** [nccgroup/ScoutSuite#457] opened 2019-06-26 08:18 UTC
In ScoutSuite seems to be counting the roles in the same account as being cross account, which Scout2 did not 

Output for Account 1234567890 (change from real account and roles) 
project-terraform-env - "arn:aws:iam::1234567890:role/project-services"

**Comment by j4v** [comment] 2019-06-26 08:39
I don't understand this issue, could you please provide more details.

**Comment by jonnieb007** [comment] 2019-06-27 06:59
I am running scoutsuite against AWS account 1234567890 and it is reporting that roles within that account are external when they are internal, so basically if account run against equals role account don't report, but if if account run against does not equals role account report.

So if running against AWS account 1234567890
arn:aws:iam::1234567890:role/project-services (don't report)
arn:aws:iam::09876545321:role/project-services (report) 

Scout2 only reported those in a different account 
arn:aws:iam::09876545321:role/project-services

Hope this helps explain it better?

**Comment by j4v** [comment] 2019-06-27 08:18
> it is reporting that roles within that account are external when they are internal

Is this in a specific finding? Where is this issue occurring?

**Comment by jonnieb007** [comment] 2019-06-27 09:41
The finding is 
AWS
IAM
Cross-account AssumeRole policy lacks external ID

We have a main account (1234567890) and then a linked account 09876545321

In Scout2 when we ran it for the main account 1234567890 it only reported those in the linked account 09876545321 as being external 

In ScoutSuite when we run it it for the main account 1234567890 it reports those in the linked account 09876545321 as being external but also roles in the main account as being external which they are not

Hope this helps?
Regards
JB

**Comment by j4v** [comment] 2019-11-12 09:27
I've tested this exact scenario and I can't reproduce your issue - I'm seeing the same-account roles being correctly filtered. 

If you look at `iam-assume-role-lacks-external-id-and-mfa.json` you can see there's a `isCrossAccount` check.

Unless you can provide more details (e.g. results JSON to validate), I'll close this as FP.

**Closed by j4v** 2019-11-12 09:27 UTC
Labels: bug, potential
