### ISSUE TITLE
GCP role bindings are merged across projects/orgs when using --all-projects

### ISSUE THREAD

**Issue by lvh** [nccgroup/ScoutSuite#258] opened 2019-03-17 00:58 UTC
Let's say you have an org O, two projects P1 and P2. Employee A has `owner` in the org, B in P1, C in P2. The Cloud Resource Manager role findings (such as "Primitive role in use`) will merge all of these, showing A, B, and C all having "owner". I inspected the JSON data and the project id (or other resource) isn't available in there either. This makes the finding not particularly useful since you don't know what resource the binding is attached to: that's necessary for both determining severity and remediation.

**Comment by j4v** [comment] 2019-03-17 10:42
This is a duplicate of https://github.com/nccgroup/ScoutSuite/issues/80 (see also https://github.com/nccgroup/ScoutSuite/issues/31). We're working on it as part of https://github.com/nccgroup/ScoutSuite/issues/183.

**Closed** 2019-03-17 10:46 UTC
Labels: bug, component-provider-gcp, duplicate

**Comment by lvh** [comment] 2019-03-17 14:59
Whoops. I saw those tickets but didn't realize they affected the CRM findings. Thanks :)
