### ISSUE TITLE
GCP organisation-wide logging sink not listed in results

### ISSUE THREAD

**Issue by mikegeoffrey** [nccgroup/ScoutSuite#30] opened 2018-11-27 13:19 UTC
Two runs ScoutSuite v4.0.3 using an organisation ID and the project ID where the logging sink resides returned no results for logging sinks under the Management->Stack Driver Logging dashboard, which is incorrect as there is one.

Confirmation there is a logging sink:

>  gcloud logging sinks list --organization=999999999

```
NAME       DESTINATION                                                         FILTER

mysink  pubsub.googleapis.com/projects/logging-project-215613/topics/mytopic  logName:logs/cloudaudit.googleapis.com%2Factivity
```

Using organisation ID:

> Scout.py --provider gcp --organization-id 999999999 --exceptions ../gcp-audit/ --report-dir ../gcp-audit/ --user-account

Using the project ID where the sink is:

> Scout.py --provider gcp --project-id logging-project-215613 --exceptions ../gcp-logging-project-audit/ --report-dir ../gcp-logging-project-audit/ --user-account`

No exceptions are reported although now I realise I should have specified a file rather than directory.

**Comment by j4v** [comment] 2018-11-27 15:41
Thanks, I'll look into this.

**Comment by j4v** [comment] 2018-11-27 18:32
I've tested it out and I do see the sink from my test environment when running with `project-id`/`organization-id`. 

Could you post `--debug` output of both runs?

**Comment by mikegeoffrey** [comment] 2018-11-28 09:54
The run using project-id didn't output any stack trace, but using organisation-id did, doesn't look that relevant to the logging sink though.  The logging sink is in project number 911645331462 with project id logging-project-215613, but I don't see any output below that shows it has enumerated that project.

```
python Scout.py --debug --provider gcp --organization-id 999999999999 --exceptions ../gcp-debug-org/ex.log --report-dir ../gcp-debug-org/ --user-account
Fetching Cloud Resource Manager config...
            projects
               54/54
Fetching Cloud Storage config...
             buckets
                 3/3
Fetching Cloud SQL config...
           instances
                 0/0
Fetching Compute Engine config...
           instances          snapshots           networks        subnetworks          firewalls
Access Not Configured. Compute Engine API has not been used in project 716814574074 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=716814574074 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 840678567100 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=840678567100 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Access Not Configured. Compute Engine API has not been used in project 479418860299 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=479418860299 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 584059900152 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=584059900152 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 663703254112 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=663703254112 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 770948436748 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=770948436748 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 1099133829256 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=1099133829256 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
             108/108                0/0                0/0                0/0                0/0Access Not Configured. Compute Engine API has not been used in project 716814574074 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=716814574074 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 840678567100 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=840678567100 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Access Not Configured. Compute Engine API has not been used in project 479418860299 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=479418860299 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 584059900152 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=584059900152 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 663703254112 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=663703254112 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 770948436748 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=770948436748 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 1099133829256 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=1099133829256 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

             108/108               1/19                0/0                0/0                0/0Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Traceback (most recent call last):
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/base/configs/base.py", line 144, in __fetch_target
    method(target, params)
  File "/home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/services/computeengine.py", line 116, in parse_snapshots
    snapshot_dict['description'] = snapshot['description'] if snapshot['description'] else 'N/A'
KeyError: 'description'

Access Not Configured. Compute Engine API has not been used in project 716814574074 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=716814574074 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 840678567100 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=840678567100 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Access Not Configured. Compute Engine API has not been used in project 479418860299 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=479418860299 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 584059900152 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=584059900152 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 663703254112 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=663703254112 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 770948436748 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=770948436748 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 1099133829256 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=1099133829256 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
             108/108               1/19                7/7                0/0                0/0Access Not Configured. Compute Engine API has not been used in project 716814574074 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=716814574074 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 840678567100 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=840678567100 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Access Not Configured. Compute Engine API has not been used in project 479418860299 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=479418860299 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 584059900152 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=584059900152 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 663703254112 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=663703254112 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 770948436748 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=770948436748 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 1099133829256 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=1099133829256 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
             108/108               1/19                7/7            126/126                0/0Access Not Configured. Compute Engine API has not been used in project 716814574074 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=716814574074 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 840678567100 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=840678567100 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Access Not Configured. Compute Engine API has not been used in project 479418860299 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=479418860299 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 584059900152 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=584059900152 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 663703254112 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=663703254112 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 770948436748 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=770948436748 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Project 1099133829256 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=1099133829256 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
             108/108               1/19                7/7            126/126              70/70
Fetching IAM config...
  projects.serviceAccounts
               14/14
Fetching Stackdriver Logging config...
               sinks
                 0/0
Loading ruleset /home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/rules/rulesets/default.json
Processing Cloud Storage rule[cloudstorage-bucket-no-versioning.json]: "Bucket without versioning"
Processing Cloud Storage rule[cloudstorage-bucket-no-logging.json]: "Bucket without logging"
Processing Cloud Storage rule[cloudstorage-bucket-member.json]: "Bucket with 'allUsers' permissions"
Processing Cloud Storage rule[cloudstorage-bucket-member.json]: "Bucket with 'allAuthenticatedUsers' permissions"
Processing Cloud SQL rule[cloudsql-instance-backups-disabled.json]: "Automatic backups disabled"
Processing Cloud SQL rule[cloudsql-instance-no-logging.json]: "Binary logging disabled"
Processing Cloud SQL rule[cloudsql-instance-ssl-not-required.json]: "SSL not required"
Processing Cloud SQL rule[cloudsql-instance-with-no-backups.json]: "Instance with no backups"
Processing Stackdriver Logging rule[stackdriverlogging-no-export-sinks.json]: "No Export Sinks"
Processing Compute Engine rule[computeengine-instance-with-deletion-protection-disabled.json]: "Instance without deletion protection"
Processing Compute Engine rule[computeengine-old-disk-snapshot.json]: "Old instance disk snapshot (over 90 days)"
Processing Compute Engine rule[computeengine-instance-disk-with-no-snapshot.json]: "Instance disk with no snapshot"
Processing Compute Engine rule[computeengine-network-with-no-instances.json]: "Network with no instances"
Processing Compute Engine rule[computeengine-firewall-rule-allows-port-range.json]: "Firewall rule allows port range(s)"
Processing Compute Engine rule[computeengine-firewall-rule-allows-all-ports.json]: "Firewall rule opens all ports (0-65535)"
Processing Compute Engine rule[computeengine-firewall-rule-opens-all-ports-to-all.json]: "Firewall rule allows public access (0.0.0.0/0) to all ports (0-65535)"
Processing Compute Engine rule[computeengine-firewall-rule-opens-sensitive-port-to-all.json]: "Firewall rule allows public access (0.0.0.0/0) to a sensitive port"
Processing Compute Engine rule[computeengine-firewall-rule-allows-internal-traffic.json]: "Firewall rule allows internal traffic"
Processing Compute Engine rule[computeengine-firewall-default-rule-in-use.json]: "Default firewall rule in use"
Processing Compute Engine rule[computeengine-firewall-rule-allows-public-access.json]: "Firewall rule allows public access (0.0.0.0/0)"
Processing Cloud Resource Manager rule[cloudresourcemanager-primitive-role-in-use.json]: "Primitive Role In Use"
Processing Cloud Resource Manager rule[cloudresourcemanager-role-assigned-to-user.json]: "IAM Role Assigned to User"
Processing IAM rule[iam-old-service-account-keys.json]: "Old Service Account Keys (over 90 days)"
Processing IAM rule[iam-service-account-user-member.json]: "Service Account with 'allUsers' Service Account User"
Processing IAM rule[iam-service-account-user-member.json]: "Service Account with 'allAuthenticatedUsers' Service Account User"
Loading ruleset /home/user/Downloads/ScoutSuite/ScoutSuite/providers/gcp/rules/rulesets/filters.json
Warning, failed to load exceptions. The file may not exist or may have an invalid format.
Searching for profiles matching ['default'] in /home/user/.aws/credentials ... 
Searching for profiles matching ['default'] in /home/user/.aws/config ... 
Saving data to ../gcp-debug-org/inc-scoutsuite-run/scoutsuite_config-gcp-999999999999.js
Saving config...
Saving data to ../gcp-debug-org/inc-scoutsuite-run/scoutsuite_exceptions-gcp-999999999999.js
Saving config...
Creating ../gcp-debug-org/report-gcp-999999999999.html ...
Opening the HTML report...
```

**Comment by j4v** [comment] 2018-11-28 10:52
Looking into this. The stackdriver logging API doesn't seem to accept any parameters (i.e. specify a project ID) so it might depend on your gcloud configuration when running Scout on an org.

**Comment by j4v** [comment] 2018-11-28 10:58
I've confirmed that the `list_sinks` call returns sinks for the default project configured in gcloud CLI.

The doc (https://googleapis.github.io/google-cloud-python/latest/logging/usage.html) doesn't seem to indicate you can request exports for a specific project, will have to look deeper into this.

**Comment by j4v** [comment] 2018-11-28 11:03
Looks like by setting the stackdriver logging client's `project` attribute to the desired project id you can pull sinks on a per-project basis. 

Will have to implement a workaround to leverage this. Will also be useful for https://github.com/nccgroup/ScoutSuite/issues/31.

**Comment by j4v** [comment] 2019-02-06 10:48
This should be fixed in https://github.com/nccgroup/ScoutSuite/pull/152.

**Comment by j4v** [comment] 2019-02-07 15:15
Closing, fixed in `develop`

**Closed by j4v** 2019-02-07 15:15 UTC
Labels: bug, component-provider-gcp
