### ISSUE TITLE
Support for AWS Gov Region

### ISSUE THREAD

**Issue by jagallardo19** [nccgroup/ScoutSuite#380] opened 2019-04-29 13:57 UTC
Good Morning,
I was wondering if this supports AWS Gov Region?

Thank you!

**Comment by j4v** [comment] 2019-04-29 13:59
@jagallardo19 I believe it does (although I haven't tested myself) - have you run into any issues?

**Comment by jagallardo19** [comment] 2019-04-29 16:57
I am currently running into these errors: 
An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials
An error occurred (InvalidClientTokenId) when calling the ListAccessKeys operation: The security token included in the request is invalid.

I checked the Username, Key and Password associated to the account we're using.

**Comment by j4v** [comment] 2019-04-29 17:07
Looks like the same as this https://github.com/nccgroup/ScoutSuite/issues/381.

We believe this is an issue on AWS's side. We're monitoring progress but for now either specify the region you wish to scan or rollback your versions of boto/botocore :smile:

**Comment by j4v** [comment] 2019-04-29 19:41
@jagallardo19 can you confirm?

**Comment by jagallardo19** [comment] 2019-04-29 20:12
Version of botocore: 1.12.125
Version of boto3: 1.9.125
Still getting the same issue.

**Comment by j4v** [comment] 2019-04-30 08:53
@jagallardo19 I guess my question was whether your issue is a duplicate of https://github.com/nccgroup/ScoutSuite/issues/381 (in which case we can close as duplicate) or if it has something to do with GovCloud?

**Comment by jagallardo19** [comment] 2019-04-30 12:34
We're looking into whether it is a duplicate of #381 right now. We should have an answer soon.

**Comment by jagallardo19** [comment] 2019-05-01 21:47
Apparently not soon. We were able to at least identify a workaround:  setting the specific region would work, but the aws-us-gov regions are not enumerated via the tool like the default "aws" partition.

**Comment by j4v** [comment] 2019-05-02 10:38
> We were able to at least identify a workaround: setting the specific region would work

Which would mean this is a duplicate of https://github.com/nccgroup/ScoutSuite/issues/381?

> the aws-us-gov regions are not enumerated via the tool like the default "aws" partition

I don't have a GovCloud account to test with so hard for me to help here...

**Comment by jagallardo19** [comment] 2019-05-13 12:49
Sorry for the delayed response. I believe it is a duplicate of #381.

**Comment by j4v** [comment] 2019-05-15 17:45
Thanks @jagallardo19.

**Closed by j4v** 2019-05-15 17:45 UTC
Labels: question
