### ISSUE TITLE
5.4.0 AWS GOV Not Working

### ISSUE THREAD

**Issue by nesdxr** [nccgroup/ScoutSuite#548] opened 2019-10-11 13:21 UTC
Running AWS using a GOV subscription produces the following console output:

```
2019-10-11 09:04:41 [host] scout[13468] INFO Fetching resources for the SQS service
... series of messages "INFO Fetching resources" for each services
2019-10-11 09:04:43 [hots] scout[13468] ERROR services.py L55: Could not fetch cloudtrail configuration: An error occurred (AuthFailure) when calling the DescribeRegions operation: AWS was not able to validate the provided access credentials
... series of AuthFailure message for all the services
```

Got this error using the `--access-keys` option. Was not able to try different authentication means since I'm running on venv. 

Same arguments work fine on 5.3.3

Found the issue coming from the call to `describe_regions` in `providers\aws\facade\base.py`.

Commenting out the logic for `ec2_not_opted_in_regions` and `not_opted_in_regions` allows me to proceed.

**Comment by j4v** [comment] 2019-10-11 14:14
Are you running the latest version of Scout/boto? Could be https://github.com/nccgroup/ScoutSuite/issues/381.

Nothing relating to govcloud has changed in ages.

**Comment by nesdxr** [comment] 2019-10-11 14:34
Yes I have the latest version, I used the requirement.txt to pull all relevant libs.

**Comment by j4v** [comment] 2019-10-11 14:46
Only thing I can think of with the above info is that your principal doesn't have privileges on the opt-in regions and that's why it is failing. Can you confirm this by running the scan against default regions only (e.g. `eu-west-1`)?

**Comment by nesdxr** [comment] 2019-10-11 14:52
I was originally running it with -r us-gov-west-1, it was the same error.

Commenting out as described in first post makes it run with or without -r us-gov-west-1.

I just tried -r eu-west-1 as advised, got same error.

**Comment by j4v** [comment] 2019-10-11 15:09
My guess is that is has to do with how `describe_regions` (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_regions) works with govcloud regions. I don't have access to a govcloud account so hard to test...

**Comment by jonathanwcrane** [comment] 2019-12-06 01:31
Can you work directly with someone from AWS on this?  I'm sure testing this tool, which AWS recomends, in GovCloud would be of benefit to them as well.  @jeffbarr

**Comment by j4v** [comment] 2019-12-07 19:30
@jonathanwcrane if you have access to a GovCloud account and are willing to lend a hand, I'm sure we can fix this.

**Comment by jonathanwcrane** [comment] 2020-01-17 13:46
Unfortunately, I'm not allowed to run ad-hoc testing for a 3rd party tool in any of the GovCloud accounts to which I have access; that's why I was hoping AWS would step in.

**Comment by j4v** [comment] 2020-01-17 14:10
Looks like there aren't any restrictions to signing up for govcloud (https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/getting-started-sign-up.html) so we should be able to test ourselves.

**Comment by rkane2002** [comment] 2020-04-06 19:05
This is caused by using govcloud credentials on commercial regions.  Govcloud has a separate IAM endpoint than commercial, and govcloud credentials are not recognized in commercial regions. 

https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/facade/base.py#L47 
https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/facade/base.py#L52
https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/facade/base.py#L56

All of those  lines use eu-west-1 as the region endpoint, which won't work with govcloud credentials.  If those are updated to use the default region for the user credentials, the code will work as expected.

Note - quick work around for govcloud users is to just change eu-west-1 to us-gov-west-1 in that file locally.

**Comment by j4v** [comment] 2020-04-07 07:31
Thanks for the background infor @rkane2002. This means that https://github.com/nccgroup/ScoutSuite/issues/685 already addresses the necessary fix?

I'll push the fix to the `develop` branch today, would you be willing/able to confirm it resolves the issue?

**Comment by j4v** [comment] 2020-04-07 12:13
Closing, this should now be resolved in `develop`. See https://github.com/nccgroup/ScoutSuite/pull/705 for new logic.

**Closed by j4v** 2020-04-07 12:13 UTC
Labels: bug, potential
