### ISSUE TITLE
Add a exclude_folders argument to exclude resource from audit

### ISSUE THREAD

**Issue by jmi926** [nccgroup/ScoutSuite#1314] opened 2021-06-08 12:19 UTC
**Is your feature request related to a problem? Please describe.**
When you have a large infra on GCP it can be useful to exclude some folders from scan, as it helps to continue audit all infra except some folders (instead of adding folders one by one with the probability to omit the new one for instance).

**Describe the solution you'd like**
I want to be able to choose some folders not to be audited by ScoutSuite.

**Describe alternatives you've considered**
I though about having a script listing all folders and have them added on command line automatically and launch the scan on each folder, but it seems more cumbersome than just add a exclude_folders flag.

**Additional context**
I have a PR ready proposing my solution on this problem (at least on GCP) by:
* Adding a new CLI parameter
* adding a check on folder recursive listing to check that the folder is not excluded
* create a function to check that the folder is in the exclude list

I think this flag would be useful for other provider as well and other GCP resource (eg. projects), tell me if you would be interested by this change.

**Comment by x4v13r64** [comment] 2021-09-16 13:42
Duplicate of https://github.com/nccgroup/ScoutSuite/issues/941.

**Closed** 2022-04-28 09:52 UTC
Labels: enhancement, component-provider-gcp
