### ISSUE TITLE
Global services logging disabled finding is not valid

### ISSUE THREAD

**Issue by NazneenRupawalla** [nccgroup/ScoutSuite#814] opened 2020-07-21 05:04 UTC
**The finding related to API activity for global services such as IAM and STS is not logged does not stand true**

Below is the output of `aws cloudtrail describe-trails`

`{
    "trailList": [
        {
            "Name": “NAME",
            "S3BucketName": “BUCKET NAME",
            "IncludeGlobalServiceEvents": true,
            "IsMultiRegionTrail": true,
            "HomeRegion": "us-east-1",
            "TrailARN": “ARN",
            "LogFileValidationEnabled": true,
            "HasCustomEventSelectors": false,
            "HasInsightSelectors": false,
            "IsOrganizationTrail": false
        }
    ]
}`

and `aws cloudtrail get-trail-status --name NAME`

`{
    "IsLogging": true,
    "LatestDeliveryTime": "2020-07-20T16:33:33.592000+05:30",
    "StartLoggingTime": "2019-02-04T23:42:56.075000+05:30",
    "LatestDigestDeliveryTime": "2020-07-20T01:21:34.470000+05:30",
    "LatestDeliveryAttemptTime": "2020-07-20T11:03:33Z",
    "LatestNotificationAttemptTime": "",
    "LatestNotificationAttemptSucceeded": "",
    "LatestDeliveryAttemptSucceeded": "2020-07-20T11:03:33Z",
    "TimeLoggingStarted": "2019-02-04T18:12:56Z",
    "TimeLoggingStopped": ""
}`

Yet global services is not being logged is flagged though logging is enabled

**Comment by j4v** [comment] 2020-07-21 07:36
@alessandrogonzalez could you review this issue please? This should have been addressed by https://github.com/nccgroup/ScoutSuite/issues/722.

@NazneenRupawalla can you confirm you're running version 5.9 (`--version`)?

**Comment by NazneenRupawalla** [comment] 2020-07-22 12:49
I indeed was running an older version. Apologies.

But with the newer version, it does not report as any resource available itself under cloudtrail which is not valid. So logging is enabled too and it should mark it as a check done against logging for global services enabled. 

<img width="1140" alt="No cloudtrail resources detected" src="https://user-images.githubusercontent.com/1947480/88178195-a323d400-cc47-11ea-9ac1-35130b683135.png">

Please let me know if I am missing anything. Thanks

**Comment by j4v** [comment] 2020-07-22 13:34
> But with the newer version, it does not report as any resource available itself under cloudtrail which is not valid. So logging is enabled too and it should mark it as a check done against logging for global services enabled.

You're saying it's *no longer* fetching the resources? That's odd, are you sure it's not to do with how you're running Scout?

**Comment by NazneenRupawalla** [comment] 2020-07-24 06:15
Yes. I ran it in the same way where in earlier it flagged that there is no logging enabled which meant it did find the resource and showed that error.
After upgrading it, it does not find the resource itself.

**Comment by alessandrogonzalez** [comment] 2020-08-14 16:44
Hi @NazneenRupawalla 

- I have tested this with the current `master` branch, which is version 5.9.1 and I could not reproduce the "empty resources" table, so it does not look broken to me.

- Based on that, and some testing, I think that you are running ScoutSuite with the `--region <region_name>` option, and the trail that you listed in your first message is not in that region. As a result, ScoutSuite only scans the resources in the region you specified with the `--region` option, and cannot know about trails in other regions (even though they could be multi-region trails). This might also explain why the resource table for the Cloudtrail service is empty (shows 0 resources).

Is that the case?

Thanks,
Alessandro

**Comment by NazneenRupawalla** [comment] 2020-08-25 12:45
So sorry for such a delayed response.

This is the command I use:
`python3 scout.py aws` (Not with the region)
I still get cloudtrail is not configured

If I run, `aws cloudtrail describe-trails` though, I get the trail information.

Thanks for looking into it.

**Comment by j4v** [comment] 2020-09-25 08:14
I've tested this myself and cannot reproduce. It correctly fetches/displays trails and their status, and the rules appropriately evaluate these values.

If you can provide the CLI output with `--debug` enabled then we can investigate further. If you don't want to post the information here, you can contact us at scoutsuite@nccgroup.com.

Closing for now.

**Closed by j4v** 2020-09-25 08:14 UTC
Labels: bug, potential
