### ISSUE TITLE
Error en OCI Certificate 

### ISSUE THREAD

**Issue by pablogarcialandeira** [nccgroup/ScoutSuite#777] opened 2020-06-08 15:38 UTC
An error message is received during the installation process regarding the version of certiifcados in Oracle OCI environments.
![7bac6800-c110-49b4-b12d-fcdda60a2e5c](https://user-images.githubusercontent.com/60926593/84051056-e20b0c80-a9ae-11ea-984d-59d221f303c4.jpg)

**Comment by ramimac** [comment] 2020-06-08 15:51
Duplicate of https://github.com/nccgroup/ScoutSuite/issues/736, please check that thread for further details

Not actually an issue with certificate, just a dependency problem.

**Closed by ramimac** 2020-06-08 15:51 UTC
Labels: bug, duplicate, potential

**Comment by j4v** [comment] 2020-06-08 17:33
I'd just add this is only an issue if you're not using a virtualenv.
