### ISSUE TITLE
Export of exceptions for ACLS allow all egress fails

### ISSUE THREAD

**Issue by museadmin** [nccgroup/ScoutSuite#93] opened 2019-01-14 14:04 UTC
Hi
I am trying to create exceptions for NACLS allowing all egress and all ingress but when I export the exceptions, I get an empty list in the json file, e.g.

`exceptions = 
{
    "vpc": {
        "vpc-default-network-acls-allow-all-egress": [
            ""
        ]
    }
}`

I don't think this is me, but to be fair I should admit that I've pulled Cloud Security Suite and swapped out Scout2 for Scout Suite on my laptop. So there's an outside chance I've broken something.

However the report looks healthy and gives me an amber warning for these. If I click on them I get the opportunity to create the exceptions. 

I've also successfully created and exported exceptions for versioned buckets without mfa delete like so:

`"s3.buckets.feb0a275b7877e07e6dc209cf336fc720ab98d.mfa_delete",`

Also, I am also only seeing the amber warnings in Safari, Chrome and FF print them in black and do not offer to create an exception if I try to click on them.

I'm also seeing an empty set for:

`"ec2": {
        "ec2-security-group-whitelists-aws": []
    },`

Can you try to reproduce this and confirm that its a bug?

Failing that could you post some examples of the correct format and I'll add the data manually.

Thanks

Brad

**Comment by j4v** [comment] 2019-01-15 14:53
Thanks for this:
- I confirm that exceptions on NACLs generate an empty list. Haven't reproduced the issue for "Security group whitelists AWS CIDRs" atm.
- Regarding amber warnings / exception on click this works for me on Chromium and FF

**Comment by museadmin** [comment] 2019-01-16 11:47
Thanks,

I revisited the amber warnings issue and can't reproduce it either. I'm also getting the whitelist ok now. This is from exactly the same report file. So perhaps this was an environmental issue on my MAC?

Thanks for looking at this.

**Comment by museadmin** [comment] 2019-01-28 11:41
I have been going through the ScoutSuite report and building up a list of filters for things we're not concerned about and I'm seeing these empty sets so far:

"vpc": {
        "vpc-default-network-acls-allow-all-ingress": [
            ""
        ],
        "vpc-default-network-acls-allow-all-egress": [
            ""
        ]
    }

"iam-assume-role-lacks-external-id-and-mfa": [],

"rds": {
        "rds-instance-no-minor-upgrade": []
    }

I'll post this here rather than raise an issue for each as they are probably related under the hood

**Comment by j4v** [comment] 2019-01-28 11:46
Thanks @museadmin, please edit the above with the instances you identify and we'll look into this.

**Comment by museadmin** [comment] 2019-02-02 10:30
Hi j4v

Sorry, I'm not sure what you mean. What I'm reporting is that I get empty arrays in the exported exclusions for the four types I mention above:

rds-instance-no-minor-upgrade
iam-assume-role-lacks-external-id-and-mfa
vpc-default-network-acls-allow-all-egress
vpc-default-network-acls-allow-all-ingress

Not sure what you mean by, "the instances". Do you mean examples from the report in the UI?

**Comment by j4v** [comment] 2019-02-02 16:01
I just meant the cases of this issue that you've identified. Thanks for sharing, we'll look into this.

**Comment by j4v** [comment] 2019-04-30 14:22
> iam-assume-role-lacks-external-id-and-mfa

I've tested this one out and it looks like a FP to me - I'm getting a value in the exception and it filters correctly.

**Comment by j4v** [comment] 2019-04-30 14:56
@museadmin this should now have been resolved by https://github.com/nccgroup/ScoutSuite/pull/387. Sorry for the delay.

Closing as fixed in `develop`.

**Closed by j4v** 2019-04-30 14:56 UTC
Labels: bug, component-UI
