### ISSUE TITLE
Azure Authentication Error

### ISSUE THREAD

**Issue by sidewinder31** [nccgroup/ScoutSuite#963] opened 2021-01-25 11:05 UTC
I am getting the below error while running ScoutSuite against an Azure Subscription

Issue occurs while running ScoutSuite on a Debian distribution, otherwise works fine on Ubuntu

`$~: python3 scout.py azure --cli --subscriptions [[redacted]] --debug  
2021-01-25 11:00:49 instance-1 scout[9500] INFO Launching Scout  
2021-01-25 11:00:49 instance-1 scout[9500] INFO Authenticating to cloud provider  
2021-01-25 11:00:50 instance-1 scout[9500] ERROR __main__.py L212: Initialization failure: type 'bool' is not an acceptable base type  

Traceback (most recent call last):  
  File "/root/ScoutSuite/ScoutSuite/__main__.py", line 212, in _run  
    cloud_provider = get_provider(provider=provider,  
  File "/root/ScoutSuite/ScoutSuite/providers/__init__.py", line 36, in get_provider  
    provider_object = get_provider_object(provider)  
  File "/root/ScoutSuite/ScoutSuite/providers/__init__.py", line 10, in get_provider_object  
    provider_module = __import__(f'ScoutSuite.providers.{provider}.provider', fromlist=[provider_class])  
  File "/root/ScoutSuite/ScoutSuite/providers/azure/provider.py", line 6, in <module>  
    from ScoutSuite.providers.azure.services import AzureServicesConfig  
  File "/root/ScoutSuite/ScoutSuite/providers/azure/services.py", line 2, in <module>  
    from ScoutSuite.providers.azure.facade.base import AzureFacade  
  File "/root/ScoutSuite/ScoutSuite/providers/azure/facade/base.py", line 6, in <module>  
    from ScoutSuite.providers.azure.facade.securitycenter import SecurityCenterFacade  
  File "/root/ScoutSuite/ScoutSuite/providers/azure/facade/securitycenter.py", line 1, in <module>  
    from azure.mgmt.security import SecurityCenter  
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/__init__.py", line 9, in <module>  
    from ._security_center import SecurityCenter  
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/_security_center.py", line 21, in <module>  
    from .operations import ComplianceResultsOperations  
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/operations/__init__.py", line 9, in <module>  
    from ._compliance_results_operations import ComplianceResultsOperations  
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/operations/_compliance_results_operations.py", line 17, in <module>  
    from .. import models  
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/models/__init__.py", line 10, in <module>  
    from ._models_py3 import AadConnectivityState  
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/models/_models_py3.py", line 14, in <module>  
    from ._security_center_enums import *  
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/models/_security_center_enums.py", line 258, in <module>  
    class Enum37(with_metaclass(_CaseInsensitiveEnumMeta, bool, Enum)):  
  File "/usr/lib/python3/dist-packages/six.py", line 856, in __new__  
    return meta(name, resolved_bases, d)  
  File "/usr/lib/python3.9/enum.py", line 171, in __new__  
    enum_class = super().__new__(metacls, cls, bases, classdict) 

TypeError: type 'bool' is not an acceptable base type`

**Comment by j4v** [comment] 2021-01-25 16:32
I see you're running python 3.9 which I'm not sure we've tested. Could you try with 3.8?

Also how have you installed the tool?

**Comment by lowSoA** [comment] 2021-01-27 12:50
As @j4v mentioned, python 3.9 could run into some errors, but 3.8 should work fine. Take a look at the wiki on [how to install](https://github.com/nccgroup/ScoutSuite/wiki/Setup#installation), otherwise you could try to run ScoutSuite in a [Docker container ](https://github.com/nccgroup/ScoutSuite/wiki/Docker-Image#running-the-container)

**Comment by j4v** [comment] 2021-01-28 10:53
@lowSoA did you confirm 3.9 is what triggers the issue? Would make sense since the dependency (https://github.com/Azure/azure-sdk-for-python) doesn't support it.

Can we close this then?

**Comment by sidewinder31** [comment] 2021-01-29 06:13
Tool works fine as on Python 3.8.5

I used the below commands to setup the tool:

`git clone https://github.com/nccgroup/ScoutSuite/
cd ScoutSuite
pip3 install -r requirements.txt
python3 setup.py install`

**Comment by j4v** [comment] 2021-01-29 11:07
Thanks @sidewinder31, in that case we'll close this issue.

**Comment by lowSoA** [comment] 2021-01-29 11:07
@sidewinder31 happy to hear that :)

@j4v, I've tried to reproduce the issue with 3.9, but didn't run into the original issue but other ones related to the dependencies in 3.9 (circular imports, etc). Guess we can close the issue and wait for dependecy support for 3.9.

**Closed** 2021-01-29 11:07 UTC
Labels: bug, component-provider-azure, potential
