### ISSUE TITLE
Exceeding GCP Service Usage API Quota

### ISSUE THREAD

**Issue by kareem-DA** [nccgroup/ScoutSuite#815] opened 2020-07-21 13:16 UTC
I am running into an issue where I am exceeding the service account quota limits for the Service Usage API.  I get the following error in my logs.   

```
2020-07-21 03:02:16 a3f49ed43909 scout[1] ERROR services.py L55: Could not fetch iam configuration: <HttpError 500 when requesting https://serviceusage.googleapis.com/v1/projects/<removed>/services?alt=json returned "Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'servicemanagement.googleapis.com' for consumer 'project_number:<removed>.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console API key', 'url': 'https://console.developers.google.com/project/<removed>/apiui/credential'}]}]">
```

It looks like good only allows 240 requests per minute.  I have submitted a ticket with google to increase the limit but I haven't gotten a response back. 
I tried rate limiting the requests with "--max-rate 1 --max-workers 3", but I am still seeing issues.

Has anyone seen this issue or have recommendations to limit the rate that scoutsuite queries the GCP api?

Parameters when calling scoutsuite
`gcp --service-account /opt/creds/gcp.json --organization-id XXXXXXXXXX --all-projects --max-rate 1 --max-workers 3`

**Comment by j4v** [comment] 2020-07-21 13:58
You're running with `--max-rate 1` and it's completing the run and/or generating the error? That's 1 request per second, unless it's faulty I don't see how that would hit a quota (unless total requests have exceeded).

**Comment by kareem-DA** [comment] 2020-07-21 14:34
Eventually, it errors out. Here is a little better of an example. The parameters I used for this run were:

gcp --service-account /opt/creds/gcp.json --organization-id <removed> --all-projects --max-rate 1 --max-workers 3 --debug

I am running scoutsuite as a docker container.  I build the image 10 days ago.  

I will see errors that look like this one several times well before the final one.  This run, I saw it 7 time before the fatal one. It's not normally right at the end.  


2020-07-21 14:11:36 bd965fcd05b7 scout[1] INFO Launching Scout
2020-07-21 14:11:36 bd965fcd05b7 scout[1] INFO Authenticating to cloud provider

<many lines removed>

2020-07-21 14:12:29 bd965fcd05b7 scout[1] ERROR services.py L55: Could not fetch iam configuration: <HttpError 429 when requesting https://serviceusage.googleapis.com/v1/projects/<removed>/services?alt=json returned "Quota exceeded for quota metric 'Default requests' and limit 'Default requests per minute' of service 'serviceusage.googleapis.com' for consumer 'project_number:<removed>'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console API key', 'url': 'https://console.developers.google.com/project/<removed>/apiui/credential'}]}]">
Traceback (most recent call last):
  File "/opt/ScoutSuite/providers/base/services.py", line 55, in _fetch
    await service_config.fetch_all(**method_args)
  File "/opt/ScoutSuite/providers/gcp/resources/projects.py", line 21, in fetch_all
    enabled = await self.facade.is_api_enabled(p['projectId'], self.__class__.__name__)
  File "/opt/ScoutSuite/providers/gcp/facade/base.py", line 141, in is_api_enabled
    services_response = await GCPFacadeUtils.get_all('services', request, services)
  File "/opt/ScoutSuite/providers/gcp/facade/utils.py", line 14, in get_all
    await run_concurrently(
  File "/opt/ScoutSuite/providers/utils.py", line 24, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/ScoutSuite/providers/gcp/facade/utils.py", line 15, in <lambda>
    lambda: GCPFacadeUtils._get_all(resources, resource_key, request, resources_group)
  File "/opt/ScoutSuite/providers/gcp/facade/utils.py", line 7, in _get_all
    response = request.execute()
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 429 when requesting https://serviceusage.googleapis.com/v1/projects/<removed>/services?alt=json returned "Quota exceeded for quota metric 'Default requests' and limit 'Default requests per minute' of service 'serviceusage.googleapis.com' for consumer 'project_number:<removed>'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console API key', 'url': 'https://console.developers.google.com/project/<removed>/apiui/credential'}]}]">

Things clear up at: 
2020-07-21 14:12:33 bd965fcd05b7 scout[1] INFO Compute Engine API not enabled for project "<removed>", skipping

A little less than a minute later I start to see errors again.  The final one is this one:

2020-07-21 14:13:14 bd965fcd05b7 scout[1] ERROR services.py L55: Could not fetch computeengine configuration: <HttpError 429 when requesting https://serviceusage.googleapis.com/v1/projects/<removed>/services?alt=json returned "Quota exceeded for quota metric 'Default requests' and limit 'Default requests per minute' of service 'serviceusage.googleapis.com' for consumer 'project_number:<removed>'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console API key', 'url': 'https://console.developers.google.com/project/<removed>/apiui/credential'}]}]">
Traceback (most recent call last):
  File "/opt/ScoutSuite/providers/base/services.py", line 55, in _fetch
    await service_config.fetch_all(**method_args)
  File "/opt/ScoutSuite/providers/gcp/resources/gce/base.py", line 19, in fetch_all
    await Projects.fetch_all(self)
  File "/opt/ScoutSuite/providers/gcp/resources/projects.py", line 21, in fetch_all
    enabled = await self.facade.is_api_enabled(p['projectId'], self.__class__.__name__)
  File "/opt/ScoutSuite/providers/gcp/facade/base.py", line 141, in is_api_enabled
    services_response = await GCPFacadeUtils.get_all('services', request, services)
  File "/opt/ScoutSuite/providers/gcp/facade/utils.py", line 14, in get_all
    await run_concurrently(
  File "/opt/ScoutSuite/providers/utils.py", line 24, in run_concurrently
    return await run_function_concurrently(function)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/ScoutSuite/providers/gcp/facade/utils.py", line 15, in <lambda>
    lambda: GCPFacadeUtils._get_all(resources, resource_key, request, resources_group)
  File "/opt/ScoutSuite/providers/gcp/facade/utils.py", line 7, in _get_all
    response = request.execute()
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 429 when requesting https://serviceusage.googleapis.com/v1/projects/<removed>/services?alt=json returned "Quota exceeded for quota metric 'Default requests' and limit 'Default requests per minute' of service 'serviceusage.googleapis.com' for consumer 'project_number:<removed>'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console API key', 'url': 'https://console.developers.google.com/project/<removed>/apiui/credential'}]}]">
Traceback (most recent call last):
  File "scout.py", line 8, in <module>
    sys.exit(run_from_cli())
  File "/opt/ScoutSuite/__main__.py", line 34, in run_from_cli
    return run(provider=args.get('provider'),
  File "/opt/ScoutSuite/__main__.py", line 131, in run
    result = loop.run_until_complete(_run(**locals()))  # pass through all the parameters
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/ScoutSuite/__main__.py", line 281, in _run
    cloud_provider.preprocessing(
  File "/opt/ScoutSuite/providers/gcp/provider.py", line 82, in preprocessing
    self._match_instances_and_snapshots()
  File "/opt/ScoutSuite/providers/gcp/provider.py", line 96, in _match_instances_and_snapshots
    for zone in project['zones'].values():
KeyError: 'zones'

**Comment by j4v** [comment] 2020-07-21 15:50
Is it possible that you aren't hitting the quota due to Scout per se, but rather other operations happening within the project(s) which already consume the daily quota? Would explain why you're hitting it despite the low max requests.

> File "/opt/ScoutSuite/providers/gcp/provider.py", line 96, in _match_instances_and_snapshots
for zone in project['zones'].values():
KeyError: 'zones'

This one looks like a (separate) bug in parsing, which we'll have to fix.

**Comment by kareem-DA** [comment] 2020-07-21 17:16
I have to admit that we do reuse that cred, but it is very lightly used.  Included is a plot of the usage for that API.  I kicked off 2 runs.  The first started at 2020-07-21 12:24:10.  It started to get API errors at 2020-07-21 12:25:15.  The second was at 2020-07-21 14:59:48.  It also exceeded the quota, but the plot shows it as just under. There was usage from another process at the start of the plot, but it didn't happen during either of the runs

![image](https://user-images.githubusercontent.com/59445682/88085462-df760800-cb53-11ea-9658-9245d9f40d8f.png)

**Comment by j4v** [comment] 2020-07-22 07:48
The odd thing is if that's the case, then it should be quite frequent that people (or us while testing) hit the quota. Any idea what's the metric? 200 requests/s ?

**Comment by kareem-DA** [comment] 2020-07-22 12:18
I think that the issue is the total number of projects we have.  We have a little under 200 projects in our org.  Google limits the service usage API to 240 requests per second.  We can request less, but not more.

**Comment by j4v** [comment] 2020-07-22 13:45
But in that case setting the max requests per second should ensure the run completes...

**Comment by kareem-DA** [comment] 2020-07-22 13:47
But it doesn't look like it is....  I am still having issues

**Comment by ramimac** [comment] 2020-09-02 21:35
@j4v I can currently reproduce this consistently when using `--all-projects` (in my case against >50,<100 projects). 

Some interesting debug notes:
1. can confirm max-rate doesn't do anything 
2. Errors of the form:

> services.py L55: Could not fetch X configuration: <HttpError 429 when requesting https://serviceusage.googleapis.com/v1/projects/PROJECT/services?alt=json&pageToken=TOKEN returned "Quota exceeded for quota metric 'Default requests' and limit 'Default requests per minute' of service 'serviceusage.googleapis.com' for consumer 'project_number:PROJECT_NUMBER'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console API key', 'url': 'https://console.developers.google.com/project/PROJECT_NUMBER/apiui/credential'}]}]">

3. I can run ScoutSuite directly against any of the projects that cause errors with no issues

**Comment by ramimac** [comment] 2020-09-03 16:09
I think it makes sense, max-rate only throttles run_concurrently AFAIK. This quota is getting popped in https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/gcp/facade/base.py _get_projects_recursively - with a large enough set of projects I believe

**Comment by kareem-DA** [comment] 2020-09-03 16:21
So digging a little deeper.  The final call is to https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/gcp/facade/utils.py

class GCPFacadeUtils:
    @staticmethod
    def _get_all(resources, resource_key: str, request, resources_group):
        while request is not None:
            response = request.execute()
            resources.extend(response.get(resource_key, []))
            request = resources_group.list_next(previous_request=request, previous_response=response)

This response is paged.  A single call to this code results in ~3 calls to the service usage api.

**Comment by ramimac** [comment] 2020-09-03 16:37
@kareem-DA _get-all is called by run_concurrently though, and so should be throttled?

**Comment by kareem-DA** [comment] 2020-09-03 17:04
Not sure where the best place to throttle is. Part of problem is that, once you get into _get_all, the code loops and that loop isn't counted in the throttling. Looks like the system usage call results in 3 pages.  Each a call to the API.  I was able to test this by putting a print statement into the code. Something like this. It will output the calls. 

        while request is not None:
            print("[{}]: {}".format(datetime.now().isoformat(), request.uri))
            response = request.execute()
            resources.extend(response.get(resource_key, []))

**Comment by j4v** [comment] 2020-09-24 10:35
> Part of problem is that, once you get into _get_all, the code loops and that loop isn't counted in the throttling.

Yep, looks like that's the problem. 

I think there's a similar situation in https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/facade/utils.py#L70, although I've not seen anyone run into issues.

**Comment by j4v** [comment] 2020-09-24 11:45
@kareem-DA, https://github.com/nccgroup/ScoutSuite/pull/875 should resolve this issue if you could please test.

**Comment by j4v** [comment] 2020-09-25 07:52
Resolved in `develop`.

**Closed by j4v** 2020-09-25 07:52 UTC
Labels: bug, component-provider-gcp
