### ISSUE TITLE
Azure Cross Cloud Request (GOV) Authentication Error

### ISSUE THREAD

**Issue by nesdxr** [nccgroup/ScoutSuite#547] opened 2019-10-11 12:59 UTC
You get the following result when you run Scout Suite 5.4.0 for Azure on a GOV subscription:

2019-10-11 08:50:06 [Host] scout[4448] INFO Launching Scout
2019-10-11 08:50:06 [Host] scout[4448] INFO Authenticating to cloud provider
2019-10-11 08:50:07 [Host] scout[4448] ERROR __main__.py L191: Authentication failure: , AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS900382: Confidential Client is not supported in Cross Cloud request.\r\nTrace ID: xx-xx-xx-xx-xx\r\nCorrelation ID: xx-xxx-xxx-xx-xxxe\r\nTimestamp: 2019-10-11 12:50:20Z","error_codes":[900382],"timestamp":"2019-10-11 12:50:20Z","trace_id":"xx-xx-xx-xx-xx","correlation_id":"xx-xx-xx-xx-xx"}

Same issue with #337 except that 337 was found on version 4.8.0.

I have the fix, pls assign this to me so I can submit a PR. Thanks.

**Comment by j4v** [comment] 2019-10-11 14:16
This is indeed a duplicate of https://github.com/nccgroup/ScoutSuite/issues/337 - we haven't implemented support for azure gov subscriptions [yet].

> I have the fix, pls assign this to me so I can submit a PR. Thanks.

Happy for you to make a PR to implement this. Not sure what you mean by "assign this to me", no privileges are required to open a PR.

**Comment by nesdxr** [comment] 2019-10-11 14:38
Looking at contributing.md, item #2 under the Getting Started section says "Assign yourself the issue". Not quite sure what that meant, this will be my first time to contribute to an open source project. I will go ahead with the PR.

Should I create the branch from the development branch? Thanks.

**Comment by j4v** [comment] 2019-10-11 14:40
> Assign yourself the issue

Ah this would be for people who are already members of the project :smile:. I've sent you an invite.

Please work from `develop` and open the PR against that branch.

**Comment by nesdxr** [comment] 2019-10-11 14:48
Thank you.

**Comment by j4v** [comment] 2019-10-15 07:44
Closing as it's a duplicate of https://github.com/nccgroup/ScoutSuite/issues/337 and being worked on in https://github.com/nccgroup/ScoutSuite/pull/550.

**Closed by j4v** 2019-10-15 07:44 UTC
Labels: duplicate
