### ISSUE TITLE
Docker no longer supports running from host

### ISSUE THREAD

**Issue by JLLeitschuh** [nccgroup/ScoutSuite#906] opened 2020-10-16 20:53 UTC
**Describe the bug**

Until recently, you could run `docker build scoutsuite:latest` in the root of the repository, then run `docker run -t --rm scoutsuite:latests scout -h` to execute scout suite and, with the right environment variables and volumes mounted get the results back on your local machine.

However, now, this is no longer possible.

**To Reproduce**

```
> docker run --rm -t rossja/ncc-scoutsuite scout
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"scout\": executable file not found in $PATH": unknown.

```

**Additional context**

My host OS is Mac OS

It would be really nice to return to a state where scout suite can be executed from the command line without having to have an interactive connection with scoutsuite.

Before, I was able to run scoutsuite as an automated CI task, but the recent docker changes have hosed my automation and I'm trying to figure out how to get back to a working state.

**Comment by j4v** [comment] 2020-10-17 08:02
Looks like a duplicate of https://github.com/nccgroup/ScoutSuite/issues/882.

Should be fixed in https://github.com/nccgroup/ScoutSuite/pull/890, will be released next week. Appreciate if you can test.

**Comment by JLLeitschuh** [comment] 2020-11-09 20:54
This is still broken on master:

```
> docker run -it scoutsuite scout
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"scout\": executable file not found in $PATH": unknown.
```

**Comment by j4v** [comment] 2020-11-10 18:07
@rossja could you please confirm?

**Comment by rossja** [comment] 2020-11-10 19:21
This looks like a blend of:

1. we moved the docker stuff out of the root of the repo, combined with 
2. rossja/ncc-scoutsuite is not the right place, and
3. the wiki here needs to be updated to not refer to the rossja docker images.

To fix:

1. there's no longer a Dockerfile in the root of this repo, which is why docker build at the repo level fails. The docker stuff has moved to the docker directory. To re-integrate with CI, clone the repo, cd $repo/docker, edit (or provide) the config/build.env vars as needed and then do either of: 
  a. run `docker-compose up --build`, or
  b. run `docker build -t scoutsuite:latest .`
  (incidental note: realigned the directory structure to support both of those options more smoothly, see [PR 925](https://github.com/nccgroup/ScoutSuite/pull/925)
2. On a broader note, I've placed the rossja/ncc-scoutsuite dockerhub repo into archived status, since it's now redundant with what's happening here (and the two have different enough approaches in the build process that things were getting messy fast).
3. The wiki page here for docker needs to be updated. I'll see if I have privs for that, and make the needed changes there if so.

**Comment by rossja** [comment] 2020-11-10 19:30
Further testing shows that running the scout command directly from outside of the container doesn't work. So, for example:

`docker run -it scoutsuite:latest scout -h` : fails
`docker run -it scoutsuite:latest bash -c scout -h` : fails 
`docker run -it scoutsuite:latest bash` : followed immediately by `scout -h` in the running container: works

There's some nuance to docker there that I'm not fully grasping, where the python venv isn't getting set up when you run the first two commands. That can be worked around by running:  `docker run -it scoutsuite:latest /root/scoutsuite/bin/scout -h`

**Comment by j4v** [comment] 2020-11-11 12:18
Thanks @rossja, this is now merged into `develop`.

**Closed by j4v** 2020-11-11 12:18 UTC
Labels: bug, duplicate

**Comment by JLLeitschuh** [comment] 2020-11-11 14:48
@j4v where was this resolved? Is there a commit or a PR link?

**Comment by j4v** [comment] 2020-11-11 16:11
https://github.com/nccgroup/ScoutSuite/pull/925

**Comment by JLLeitschuh** [comment] 2020-11-11 17:32
I can confirm on develop that `docker run -it scoutsuite:latest /root/scoutsuite/bin/scout -h` works. Is this path guaranteed to be fixed moving forward? `docker run -it scoutsuite:latest scout -h`still does not work, so if I'm going to move forward with the absolute path, I'd hope the path won't change.

**Comment by rossja** [comment] 2020-11-11 18:11
That path has not changed since the initial version was pushed to rossja/ncc-scoutsuite. I can't guarantee that it *never* will, but there are no plans to move it, and I see no reason it should change.
