### ISSUE TITLE
CreationDate reported for S3 buckets is incorrect

### ISSUE THREAD

**Issue by margaretho** [nccgroup/ScoutSuite#858] opened 2020-09-16 21:05 UTC
I noticed in my recent scans that the Creation Dates reported for all of my S3 buckets are incorrect. None of the reported Creation Dates are before 2018, when there are much older buckets in the scanned account, and the more recently created buckets have a reported date that is off, as well. This didn't occur in a scan that I ran in July of this year.

**Comment by j4v** [comment] 2020-09-17 07:01
Doubt this is a Scout issue, as we're just pulling the creation date from the API:

See https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/aws/resources/s3/buckets.py#L28

**Comment by lowSoA** [comment] 2020-11-11 11:10
Hi @margaretho, this seems to be the expected behaviour by the AWS SDK as mentioned [here](https://github.com/aws/aws-cli/issues/3597#issuecomment-424167129).

Should be fixed in #926 (`bug/858-s3-incorrect-creationdate`). Appreciate if you can test.

**Comment by j4v** [comment] 2020-11-13 11:27
Thanks @lowSoA, closing as https://github.com/nccgroup/ScoutSuite/pull/926 has been merged.

**Closed by j4v** 2020-11-13 11:27 UTC
Labels: bug, component-provider-aws, potential
