### ISSUE TITLE
provider.py L376: list index out of range

### ISSUE THREAD

**Issue by heydonovan** [nccgroup/ScoutSuite#427] opened 2019-05-22 15:59 UTC
First time using this tool, but it's great so far! I ran into the boto issue that's currently pinned, but was able to get around it by running: `scout aws --profile scout --regions us-east-1`

However, ran into a few errors as well (even though the report generated just fine):

```
$ scout aws --profile scout --regions us-east-1
scout[9840] INFO Launching Scout
scout[9840] INFO Authenticating to cloud provider
scout[9840] INFO Gathering data from APIs
scout[9840] INFO Fetching resources for the Lambda service
scout[9840] INFO Fetching resources for the CloudFormation service
scout[9840] INFO Fetching resources for the CloudTrail service
scout[9840] INFO Fetching resources for the CloudWatch service
scout[9840] INFO Fetching resources for the Config service
scout[9840] INFO Fetching resources for the Direct Connect service
scout[9840] INFO Fetching resources for the EC2 service
scout[9840] INFO Fetching resources for the EFS service
scout[9840] INFO Fetching resources for the ElastiCache service
scout[9840] INFO Fetching resources for the ELB service
scout[9840] INFO Fetching resources for the ELBv2 service
scout[9840] INFO Fetching resources for the EMR service
scout[9840] INFO Fetching resources for the IAM service
scout[9840] INFO Fetching resources for the RDS service
scout[9840] INFO Fetching resources for the RedShift service
scout[9840] INFO Fetching resources for the Route53 service
scout[9840] INFO Fetching resources for the S3 service
scout[9840] INFO Fetching resources for the SES service
scout[9840] INFO Fetching resources for the SNS service
scout[9840] INFO Fetching resources for the SQS service
scout[9840] INFO Fetching resources for the VPC service
scout[9840] ERROR provider.py L322: 'UserId'
scout[9840] ERROR provider.py L322: 'UserId'
scout[9840] INFO Matching EC2 instances and IAM roles
scout[9840] INFO Processing CloudTrail config
scout[9840] ERROR provider.py L376: list index out of range
scout[9840] INFO Running rule engine
scout[9840] INFO Applying display filters
scout[9840] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_aws-scout.js
scout[9840] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_aws-scout.js
scout[9840] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_errors_aws-scout.json
scout[9840] INFO Creating scoutsuite-report/aws-scout.html
scout[9840] INFO Opening the HTML report
```

**Comment by j4v** [comment] 2019-05-22 16:00
Thanks for this, could you please run with `--debug` and provide the content of the `scoutsuite-report/scoutsuite-results/scoutsuite_errors_aws-scout.json` file?

**Comment by heydonovan** [comment] 2019-05-22 16:17
```
(venv) bash-5.0$ cat scoutsuite_errors_aws-scout.json
[
    {
        "additional_details": {
            "current path": "['regions', 'us-east-1', 'vpcs', 'vpc-7f73fb13', 'security_groups', 'sg-8f5004f4', 'rules', 'ingress', 'protocols', 'TCP', 'ports', '601-602', 'security_groups']",
            "key": "security_groups",
            "path": "[]",
            "value": "{'GroupId': 'sg-7f82d61a', 'PeeringStatus': 'deleted', 'VpcId': 'vpc-0ee9416b'}"
        },
        "exception": "'UserId'",
        "file": "provider.py",
        "line": 322,
        "traceback": "Traceback (most recent call last):\n  File \"/Users/heydonovan/venv/lib/python3.6/site-packages/ScoutSuite/providers/base/provider.py\", line 322, in _go_to_and_do\n    callback(current_config, path, current_path, value, callback_args)\n  File \"/Users/heydonovan/venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/provider.py\", line 177, in add_security_group_name_to_ec2_grants_callback\n    elif ec2_grant['UserId'] == callback_args['AWSAccountId']:\nKeyError: 'UserId'\n"
    },
    {
        "additional_details": {
            "current path": "['regions', 'us-east-1', 'vpcs', 'vpc-7f73fb13', 'security_groups', 'sg-ae6a21d5', 'rules', 'ingress', 'protocols', 'TCP', 'ports', '20514', 'security_groups']",
            "key": "security_groups",
            "path": "[]",
            "value": "{'GroupId': 'sg-7f82d61a', 'PeeringStatus': 'deleted', 'VpcId': 'vpc-0ee9416b'}"
        },
        "exception": "'UserId'",
        "file": "provider.py",
        "line": 322,
        "traceback": "Traceback (most recent call last):\n  File \"/Users/heydonovan/venv/lib/python3.6/site-packages/ScoutSuite/providers/base/provider.py\", line 322, in _go_to_and_do\n    callback(current_config, path, current_path, value, callback_args)\n  File \"/Users/heydonovan/venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/provider.py\", line 177, in add_security_group_name_to_ec2_grants_callback\n    elif ec2_grant['UserId'] == callback_args['AWSAccountId']:\nKeyError: 'UserId'\n"
    },
    {
        "additional_details": {
            "callback": "match_security_groups_and_resources_callback",
            "callback arguments": {
                "sg_list_attribute_name": [
                    "VpcConfig",
                    "SecurityGroupIds"
                ],
                "status_path": [
                    "Runtime"
                ]
            },
            "current path": "['services', 'awslambda', 'regions', 'us-east-1', 'functions']",
            "key": "functions",
            "path": "[]",
            "value": "test-REDACTED-deploy"
        },
        "exception": "list index out of range",
        "file": "provider.py",
        "line": 376,
        "traceback": "Traceback (most recent call last):\n  File \"/Users/heydonovan/venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/provider.py\", line 520, in match_security_groups_and_resources_callback\n    vpc_id = self.sg_map[sg_id]['vpc_id']\nKeyError: 'sg-7d0e810d'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/heydonovan/venv/lib/python3.6/site-packages/ScoutSuite/providers/base/provider.py\", line 376, in _new_go_to_and_do\n    callback_args)\n  File \"/Users/heydonovan/venv/lib/python3.6/site-packages/ScoutSuite/providers/aws/provider.py\", line 549, in match_security_groups_and_resources_callback\n    vpc_id = current_path[5]\nIndexError: list index out of range\n"
    }
]
```

**Comment by j4v** [comment] 2019-05-22 16:43
Could you run the `bugfix/issues/427` branch and post back the results? Seems like there's a new grant type we haven't seen.

Looking into the second error, I believe it's caused by a lambda function running in a VPC.

**Comment by heydonovan** [comment] 2019-05-22 17:11
```
(venv) bash-5.0$ git branch
* (HEAD detached at origin/bugfix/issues/427)
  master
```

```
(venv) bash-5.0$ python scout.py aws --profile scout --regions us-east-1
scout[19762] INFO Launching Scout
scout[19762] INFO Authenticating to cloud provider
scout[19762] INFO Gathering data from APIs
scout[19762] INFO Fetching resources for the Lambda service
scout[19762] INFO Fetching resources for the CloudFormation service
scout[19762] INFO Fetching resources for the CloudTrail service
scout[19762] INFO Fetching resources for the CloudWatch service
scout[19762] INFO Fetching resources for the Config service
scout[19762] INFO Fetching resources for the Direct Connect service
scout[19762] INFO Fetching resources for the EC2 service
scout[19762] INFO Fetching resources for the EFS service
scout[19762] INFO Fetching resources for the ElastiCache service
scout[19762] INFO Fetching resources for the ELB service
scout[19762] INFO Fetching resources for the ELBv2 service
scout[19762] INFO Fetching resources for the EMR service
scout[19762] INFO Fetching resources for the IAM service
scout[19762] INFO Fetching resources for the RDS service
scout[19762] INFO Fetching resources for the RedShift service
scout[19762] INFO Fetching resources for the Route53 service
scout[19762] INFO Fetching resources for the S3 service
scout[19762] INFO Fetching resources for the SES service
scout[19762] INFO Fetching resources for the SNS service
scout[19762] INFO Fetching resources for the SQS service
scout[19762] INFO Fetching resources for the VPC service
scout[19762] ERROR Failed to handle EC2 grant: {'GroupId': 'sg-7f82d61a', 'PeeringStatus': 'deleted', 'VpcId': 'vpc-0ee9416b'}
scout[19762] ERROR Failed to handle EC2 grant: {'GroupId': 'sg-7f82d61a', 'PeeringStatus': 'deleted', 'VpcId': 'vpc-0ee9416b'}
scout[19762] INFO Matching EC2 instances and IAM roles
scout[19762] INFO Processing CloudTrail config
scout[19762] ERROR provider.py L376: list index out of range
scout[19762] INFO Running rule engine
scout[19762] INFO Applying display filters
scout[19762] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_aws-scout.js
scout[19762] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_aws-scout.js
scout[19762] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_errors_aws-scout.json
scout[19762] INFO Creating scoutsuite-report/aws-scout.html
scout[19762] INFO Opening the HTML report
```

```
(venv) bash-5.0$ cat scoutsuite_errors_aws-scout.json
[
    {
        "additional_details": null,
        "exception": "Failed to handle EC2 grant: {'GroupId': 'sg-7f82d61a', 'PeeringStatus': 'deleted', 'VpcId': 'vpc-0ee9416b'}",
        "file": null,
        "line": null,
        "traceback": "None"
    },
    {
        "additional_details": null,
        "exception": "Failed to handle EC2 grant: {'GroupId': 'sg-7f82d61a', 'PeeringStatus': 'deleted', 'VpcId': 'vpc-0ee9416b'}",
        "file": null,
        "line": null,
        "traceback": "None"
    },
    {
        "additional_details": {
            "callback": "match_security_groups_and_resources_callback",
            "callback arguments": {
                "sg_list_attribute_name": [
                    "VpcConfig",
                    "SecurityGroupIds"
                ],
                "status_path": [
                    "Runtime"
                ]
            },
            "current path": "['services', 'awslambda', 'regions', 'us-east-1', 'functions']",
            "key": "functions",
            "path": "[]",
            "value": "test-REDACTED-deploy"
        },
        "exception": "list index out of range",
        "file": "provider.py",
        "line": 376,
        "traceback": "Traceback (most recent call last):\n  File \"/Users/heydonovan/ScoutSuite/ScoutSuite/providers/aws/provider.py\", line 522, in match_security_groups_and_resources_callback\n    vpc_id = self.sg_map[sg_id]['vpc_id']\nKeyError: 'sg-7d0e810d'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/heydonovan/ScoutSuite/ScoutSuite/providers/base/provider.py\", line 376, in _new_go_to_and_do\n    callback_args)\n  File \"/Users/heydonovan/ScoutSuite/ScoutSuite/providers/aws/provider.py\", line 551, in match_security_groups_and_resources_callback\n    vpc_id = current_path[5]\nIndexError: list index out of range\n"
    }
]
```

**Comment by j4v** [comment] 2019-05-23 12:07
Right so the first issue should now be handled and was no biggie.

The second one I haven't been able to reproduce. Do you have an odd network config for the Lambda function? 
`bugfix/issues/427` should now provide a better exception message, could you re-run please?

**Comment by heydonovan** [comment] 2019-05-24 00:01
```
scout[36950] INFO Processing CloudTrail config
scout[36950] ERROR provider.py L522: Failed to parse functions: 'sg-7d0e810d'
scout[36950] INFO Running rule engine
```

```
$ cat scoutsuite_errors_aws-scout.json
[
    {
        "additional_details": null,
        "exception": "Failed to parse functions: 'sg-7d0e810d'",
        "file": "provider.py",
        "line": 522,
        "traceback": "Traceback (most recent call last):\n  File \"/Users/heydonovan/ScoutSuite/ScoutSuite/providers/aws/provider.py\", line 522, in match_security_groups_and_resources_callback\n    vpc_id = self.sg_map[sg_id]['vpc_id']\nKeyError: 'sg-7d0e810d'\n"
    }
]
```

```
$ aws ec2 describe-security-groups --group-ids sg-7d0e810d

An error occurred (InvalidGroup.NotFound) when calling the DescribeSecurityGroups operation: The security group 'sg-7d0e810d' does not exist
```

Where is it pulling `sg-7d0e810d` from? 🤔

**Comment by heydonovan** [comment] 2019-05-24 00:06
Very interesting! It seems the `test-REDACTED-deploy` lambda function is referencing a security group that doesn't exist. Or maybe used to exist. How does AWS even allow that 😂 

![image](https://user-images.githubusercontent.com/918946/58294064-c6c26480-7d8d-11e9-836c-b342379bb5bd.png)

**Comment by j4v** [comment] 2019-05-24 08:58
> It seems the test-REDACTED-deploy lambda function is referencing a security group that doesn't exist.

That's quite odd, I would think it should at least raise a warning if the SG didn't exist anymore.

The first issue was caused by a VPC peering configuration but I don't think you can assign an SG to a lambda function from a peered VPC!!! I'll have to test it out.

**Comment by j4v** [comment] 2019-06-07 09:42
> That's quite odd, I would think it should at least raise a warning if the SG didn't exist anymore.

Couldn't reproduce this. Closing as the other element is resolved in `develop`.

**Closed by j4v** 2019-06-07 09:42 UTC
Labels: bug, potential
