### ISSUE TITLE
Azure Cloud (21Vianet China)

### ISSUE THREAD

**Issue by winnettjohnston** [nccgroup/ScoutSuite#1029] opened 2021-02-11 21:47 UTC
**Describe the bug**
The scout suite is not honoring the az cloud set command
```az cloud set --name AzureChinaCloud ```

```
(scoutsuite) root@5368ab849695:~# scout azure --cli --no-browser --report-dir /root/scout-report/ --debug
2021-02-11 21:07:38 5368ab849695 scout[77] INFO Launching Scout
2021-02-11 21:07:38 5368ab849695 scout[77] INFO Authenticating to cloud provider
2021-02-11 21:07:39 5368ab849695 scout[77] ERROR __main__.py L212: Initialization failure: Azure Error: AuthenticationFailed
Message: Authentication failed.
Traceback (most recent call last):
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/__main__.py", line 212, in _run
    cloud_provider = get_provider(provider=provider,
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/__init__.py", line 37, in get_provider
    provider_instance = provider_object(profile=profile,
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/azure/provider.py", line 44, in __init__
```

**To Reproduce**

```
sudo docker run -it rossja/ncc-scoutsuite bash
pip3 install azure-cli
az cloud set --name AzureChinaCloud
az login
```

**Output**

```
To sign in, use a web browser to open the page https://microsoft.com/deviceloginchina and enter the code XXXXXXXXX to authenticate.
[
  {
    "cloudName": "AzureChinaCloud",
    "homeTenantId": "XXXXXXXX-xxxx-xxxx-xxxx-XXXXXXXXXXXX",
    "id": "XXXXXXXX-xxxx-xxxx-xxxx-XXXXXXXXXXXX",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Standard Pay-in-Advance Offer",
    "state": "Enabled",
    "tenantId": "XXXXXXXX-xxxx-xxxx-xxxx-XXXXXXXXXXXX",
    "user": {
      "name": "user@domain.com",
      "type": "user"
    }
  }
]
```

**run scout**
```scout azure --cli --no-browser --report-dir /root/scout-report/ --debug```

**Output**
```
2021-02-11 21:07:38 5368ab849695 scout[77] INFO Launching Scout
2021-02-11 21:07:38 5368ab849695 scout[77] INFO Authenticating to cloud provider
2021-02-11 21:07:39 5368ab849695 scout[77] ERROR __main__.py L212: Initialization failure: Azure Error: AuthenticationFailed
Message: Authentication failed.
Traceback (most recent call last):
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/__main__.py", line 212, in _run
    cloud_provider = get_provider(provider=provider,
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/__init__.py", line 37, in get_provider
    provider_instance = provider_object(profile=profile,
  File "/root/scoutsuite/lib/python3.8/site-packages/ScoutSuite/providers/azure/provider.py", line 44, in __init__
```

**Comment by j4v** [comment] 2021-02-12 09:18
This looks like a duplicate of https://github.com/nccgroup/ScoutSuite/issues/836. We currently don't support China region and don't have an account to test/implement - PRs are welcome!. 

We're re-implementing the authentication with Azure Identity (https://github.com/nccgroup/ScoutSuite/pull/1026), which may resolve this though.

**Closed by j4v** 2021-02-12 09:18 UTC
Labels: bug, duplicate
