### ISSUE TITLE
'MonitorManagementClient' from 'azure.mgmt.monitor' 

### ISSUE THREAD

**Issue by fetchem** [nccgroup/ScoutSuite#894] opened 2020-10-13 18:51 UTC
I'm getting this error when I first kick off a job.  Any ideas?

 __main__.py L212: Initialization failure: cannot import name 'MonitorManagementClient' from 'azure.mgmt.monitor'

**Comment by j4v** [comment] 2020-10-14 06:44
Duplicate of https://github.com/nccgroup/ScoutSuite/issues/861.

Ensure you are running the latest version of Scout (5.10) and that you've upgraded your dependencies.

**Closed by j4v** 2020-10-14 06:44 UTC
Labels: bug, potential
