### ISSUE TITLE
oci requires cryptography==2.8 while aliyun-python-sdk-core requires cryptography>=2.9.2,  this fails pip install 

### ISSUE THREAD

**Issue by mhoykpmg** [nccgroup/ScoutSuite#934] opened 2020-11-24 15:44 UTC
- While installing with pip the following error is shown 
`oci 2.24.0 requires cryptography==2.8, but you'll have cryptography 3.2.1 which is incompatible.`
- Running `scout --help`
`pkg_resources.DistributionNotFound: The 'cryptography==2.8' distribution was not found and is required by oci`
- Trying to install the specific version of cryptography with `pip install cryptography==2.8` results in another package complaining.
`aliyun-python-sdk-core 2.13.29 requires cryptography>=2.9.2, but you'll have cryptography 2.8 which is incompatible.`
`pkg_resources.ContextualVersionConflict: (cryptography 2.8 (/Users/mhoy/.pyenv/versions/3.8.6/envs/venv/lib/python3.8/site-packages), Requirement.parse('cryptography>=2.9.2'), {'aliyun-python-sdk-core'})`

**To Reproduce**
Using python 3.8.6 on Mac OS
`pip install scoutsuite`

**Comment by j4v** [comment] 2020-11-24 15:54
This is a duplicate of https://github.com/nccgroup/ScoutSuite/issues/736. The "fix" is to use a virtualenv.

**Closed by j4v** 2020-11-24 15:54 UTC
Labels: bug, potential

**Comment by mhoykpmg** [comment] 2020-11-24 16:12
Thanks for the quick reply. I should have mentioned I am running this inside venv.
https://docs.python.org/3/library/venv.html

Am I right in understanding this only works when running inside virtualenv? 
https://virtualenv.pypa.io/en/latest/

**Comment by j4v** [comment] 2020-11-24 17:28
> Am I right in understanding this only works when running inside virtualenv?

As far as I know yes.
