### ISSUE TITLE
ModuleNotFoundError: No module named 'asyncio_throttle' 

### ISSUE THREAD

**Issue by battlesysadmin** [nccgroup/ScoutSuite#743] opened 2020-05-15 17:18 UTC
On both Mac and Linux, I was unable to run _Scoutsuite_ until I did two pre-steps. I ran these steps from the _ScoutSuite_ directory.

1.  `pip3 install -r ./requirements.txt`
2. `python3 ./setup.py install`

Until I found this workaround, I would get an **asyncio_throttle** error, despite checking paths, versions, libraries, and everything else I could think of.

This is an example of a typical error:

```
Traceback (most recent call last):
  File "./scout.py", line 5, in <module>
    from ScoutSuite.__main__ import run_from_cli
  File "/Users/username/WORK/audits/dev1/ScoutSuite/ScoutSuite/__main__.py", line 8, in <module>
    from asyncio_throttle import Throttler
ModuleNotFoundError: No module named 'asyncio_throttle'
```

**Comment by ramimac** [comment] 2020-05-15 17:25
Just to clarify @battlesysadmin, are you saying the setup steps didn't work for you? https://github.com/nccgroup/ScoutSuite/wiki/Setup

Otherwise, this is as expected - you need to install the requirements (which includes asyncio_throttle - see line 8 https://github.com/nccgroup/ScoutSuite/blob/master/requirements.txt) before you can run ScoutSuite.

**Comment by j4v** [comment] 2020-05-16 15:07
This looks like a non-issue to me. Closing unless we get more info.

**Closed by j4v** 2020-05-16 15:07 UTC

**Comment by chrisdlangton** [comment] 2022-05-06 07:41
Occurs for me also
```sh
python --version # Python 3.10.4
git clone https://github.com/nccgroup/ScoutSuite scoutsuite
cd scoutsuite
python -m venv .venv
source .venv/bin/activate
pip install -r ./requirements.txt # result below
python scout.py --help # same error
```

The `requirements.txt` (or any of the installed packages) simply doesn't include `asyncio_throttle` so the error is obvious. This is what is installed on a fresh install of WSL/Ubuntu and verified identical on Ubuntu 22.04 in a VM

```
Successfully installed PyJWT-1.7.1 adal-1.2.4 aliyun-python-sdk-actiontrail-2.0.4 aliyun-python-sdk-core-2.13.36 aliyun-python-sdk-ecs-4.24.17 aliyun-python-sdk-kms-2.15.0 aliyun-python-sdk-ocs-0.0.4 aliyun-python-sdk-ram-3.2.0 aliyun-python-sdk-rds-2.6.1 aliyun-python-sdk-sts-3.1.0 aliyun-python-sdk-vpc-3.0.16 applicationinsights-0.11.10 argcomplete-1.12.3 asyncio-throttle-0.1.1 azure-cli-core-2.12.0 azure-cli-telemetry-1.0.6 azure-common-1.1.28 azure-core-1.23.1 azure-graphrbac-0.61.1 azure-mgmt-authorization-0.60.0 azure-mgmt-compute-12.0.0 azure-mgmt-core-1.2.0 azure-mgmt-keyvault-1.1.0 azure-mgmt-monitor-0.5.2 azure-mgmt-network-2.5.1 azure-mgmt-nspkg-3.0.2 azure-mgmt-redis-6.0.0 azure-mgmt-resource-10.2.0 azure-mgmt-security-0.4.1 azure-mgmt-sql-0.11.0 azure-mgmt-storage-7.1.0 azure-mgmt-web-0.47.0 azure-nspkg-3.0.2 bcrypt-3.2.2 boto3-1.22.8 botocore-1.25.8 cachetools-4.2.4 certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.12 cheroot-8.6.0 cherrypy-18.6.1 cherrypy-cors-1.6 circuitbreaker-1.3.2 colorama-0.4.4 coloredlogs-10.0 crcmod-1.7 cryptography-3.4.7 google-api-core-1.31.5 google-api-python-client-2.47.0 google-auth-1.35.0 google-auth-httplib2-0.1.0 google-cloud-appengine-logging-1.1.1 google-cloud-audit-log-0.2.0 google-cloud-container-2.10.7 google-cloud-core-2.3.0 google-cloud-iam-2.6.1 google-cloud-kms-1.3.0 google-cloud-logging-3.0.0 google-cloud-monitoring-1.1.0 google-cloud-resource-manager-1.4.1 google-cloud-storage-2.3.0 google-crc32c-1.3.0 google-resumable-media-2.3.2 googleapis-common-protos-1.56.0 grpc-google-iam-v1-0.12.4 grpcio-1.46.0 httpagentparser-1.9.2 httplib2-0.20.4 httplib2shim-0.0.3 humanfriendly-8.2 idna-3.3 isodate-0.6.1 jaraco.classes-3.2.1 jaraco.collections-3.5.1 jaraco.context-4.1.1 jaraco.functools-3.5.0 jaraco.text-3.7.0 jmespath-0.10.0 knack-0.7.2 more-itertools-8.12.0 msal-1.0.0 msal-extensions-0.1.3 msrest-0.6.21 msrestazure-0.6.4 netaddr-0.8.0 oauth2client-4.1.3 oauthlib-3.2.0 oci-2.66.0 oss2-2.15.0 packaging-21.3 paramiko-2.10.4 pkginfo-1.8.2 policyuniverse-1.5.0.20220426 portalocker-1.7.1 portend-3.1.0 proto-plus-1.20.3 protobuf-3.20.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pycryptodome-3.14.1 pygments-2.12.0 pynacl-1.5.0 pyopenssl-19.1.0 pyparsing-3.0.8 python-dateutil-2.8.0 pytz-2022.1 pyyaml-6.0 requests-2.27.1 requests-oauthlib-1.3.1 rsa-4.8 s3transfer-0.5.2 six-1.16.0 sqlitedict-2.0.0 tabulate-0.8.9 tempora-5.0.1 typing-extensions-4.2.0 uritemplate-4.1.1 urllib3-1.26.9 zc.lockfile-2.0
```

Just a note to maintainers; to close this report is to not have even tried to run the current master branch, which is poor form from maintainers to not even try to reproduce this, or even run this project themselves... Just FYI, ignore if you will

**Comment by chr4ss12** [comment] 2023-02-17 20:06
this is a bug that should be fixed

**Comment by BMR0N** [comment] 2023-11-07 10:02
After a bit of trial and error, I find that this usually occurs when the user is running their source /bin/venv/activate from a different directory than where they ran the initial install (i.e. outside of the scoutsuite directory).

So below, we have me activating a venv instance from my home directory, navigating to scout directory and attempting to run it. This results in the error as it appears venv cant see that the modules exist because venv isn't operating from where it should be.
`┌──( BMR0N㉿Kali)-[~]

└─$ source venv/bin/activate

 

(venv) ┌──(BMR0N㉿Kali)-[~]

└─$ python3 ~ /scoutsuite/scout.py aws

Traceback (most recent call last):

  File "/home/BMR0N/scoutsuite/scout.py", line 5, in <module>

    from ScoutSuite.__main__ import run_from_cli

  File "/home/BMR0N/scoutsuite/ScoutSuite/__main__.py", line 5, in <module>

    from asyncio_throttle import Throttler

ModuleNotFoundError: No module named 'asyncio_throttle'`

Now that we have moved into the correct directory and activated venv, it can see all the modules it expects and runs fine.

`┌──( BMR0N㉿Kali)-[~/ scoutsuite]

└─$ source venv/bin/activate


┌──( BMR0N㉿Kali)-[~/scoutsuite]

└─$ python3 scout.py aws

2023-11-07 09:54:08 KaliRon scout[284671] INFO Launching Scout`
