### ISSUE TITLE
AWS Instance Role

### ISSUE THREAD

**Issue by lee5i3** [nccgroup/ScoutSuite#524] opened 2019-09-18 16:29 UTC
I am running scout on a server that already has access to AWS via an IAM role

How can I get scout to ignore the keys?

When I try
`
python scout.py aws --region us-east-1 us-west-1 us-west-2
`
its saying I need to pass in either --access-keys or --profile which neither I have inside AWS

**Comment by j4v** [comment] 2019-09-18 16:31
Duplicate of https://github.com/nccgroup/ScoutSuite/issues/509 and https://github.com/nccgroup/ScoutSuite/issues/523, should be fixed in `develop`.

**Comment by lee5i3** [comment] 2019-09-18 16:32
thanks, i will pull down develop until its fixed in master

**Closed by j4v** 2019-09-18 16:31 UTC
