### ISSUE TITLE
Scout "killed" by the OS

### ISSUE THREAD

**Issue by dataatsky** [nccgroup/ScoutSuite#819] opened 2020-07-24 10:10 UTC
**Describe the bug**

Scout version: 5.9

Scout is killed by the OS(Ubuntu Linux 18.04) when running it against a specific subscription in Azure. I can see with "top" that RAM goes all the way up and even fills the SWAP. After that you see "Killed". Running it with "--debug" makes no difference in the output. I currently have 6GB of RAM and 2GB SWAP. I can increase the RAM up to 10GB or so but I wonder if there should be a memory management module developed so these things don't happen.

Let me know what information you need more from me and how I can obtain for this issue to be resolved as this is a production subscription and we need to run it there.

Thank you

- The **exact** CLI parameters used to run Scout Suite.
./scout.py azure --tenant xxx-xxx-xxx-xxx-xxx --subscriptions xxx-xxx-xxx-xxx-xxx-xxx --user-account-browser --debug
- Any specific configuration within the cloud account which might have lead to the issue.
Nothing specific.

**Comment by j4v** [comment] 2020-07-24 10:24
To confirm, you are running Scout against a single subscription? This is likely caused by https://github.com/nccgroup/ScoutSuite/issues/793.

**Comment by dataatsky** [comment] 2020-07-24 10:29
Yea, this is for a single subscription. When do you think 5.10 will be released?

Thank you

**Comment by j4v** [comment] 2020-07-24 11:01
> When do you think 5.10 will be released?

Within the next 2 months most likely, but this issue will be addresses much sooner.

Closing this as a duplicate.

**Closed by j4v** 2020-07-24 11:01 UTC
Labels: bug, component-provider-azure, duplicate, potential
