### ISSUE TITLE
Cli Error while running Scout2 commands

### ISSUE THREAD

**Issue by challs1** [nccgroup/ScoutSuite#409] opened 2019-05-13 21:29 UTC
We are getting these errors for all the services when rounning scout2 on aws ec2 linux server. Already removed the cache and tried to run the Scout2 but still we are getting same issue . Kindly help us in getting this issue resolved.

Fetching RDS config...
             regions   parameter_groups          instances          snapshots    security_groups      subnet_groups
An error occurred (InvalidClientTokenId) when calling the DescribeDBParameterGroups operation: The security token included in the request is invalid
An error occurred (InvalidClientTokenId) when calling the DescribeDBInstances operation: The security token included in the request is invalid
                0/17                0/0                0/0                0/0                1/1                0/0An error occurred (InvalidClientTokenId) when calling the DescribeDBSnapshots operation: The security token included in the request is invalid
                2/17                0/0                0/0                0/0                4/4                0/0An error occurred (InvalidClientTokenId) when calling the DescribeDBSubnetGroups operation: The security token included in the request is invalid

               17/17                0/0                0/0                0/0              16/16                0/0
Fetching CloudTrail config...
             regions             trails
                2/17                4/4An error occurred (UnrecognizedClientException) when calling the DescribeTrails operation: The security token included in the request is invalid
               16/17              29/30'str' object has no attribute 'strftime'
               17/17              31/32

**Comment by j4v** [comment] 2019-05-15 17:40
Looks like a duplicate of https://github.com/nccgroup/ScoutSuite/issues/381. Please advise if that is not the case.

**Closed by j4v** 2019-05-15 17:40 UTC
Labels: duplicate
