### ISSUE TITLE
cloud trail wildcard detection bug

### ISSUE THREAD

**Issue by regevbr** [nccgroup/ScoutSuite#514] opened 2019-08-29 16:33 UTC
The check for wildcard s3 data logging is not working.

The reason is that is searchs for `arn:aws:s3:::` wheres the configuration only has `arn:aws:s3` when wildcard is set

The relevant code:

https://github.com/nccgroup/ScoutSuite/blob/faadf03bc0ecd3a628003901d6961c1fe35d1668/ScoutSuite/providers/aws/resources/cloudtrail/trails.py#L52-L61

**Comment by j4v** [comment] 2019-09-11 14:43
Thanks for raising this, will look into it.

**Comment by j4v** [comment] 2019-10-09 09:54
@regevbr could you please test https://github.com/nccgroup/ScoutSuite/pull/540 to confirm this is resolved?

**Comment by regevbr** [comment] 2019-10-10 14:59
@j4v sure, will keep you posted

**Comment by regevbr** [comment] 2019-10-10 15:45
@j4v thanks that fixes the problem!
The issue I'm facing now is that all my s3 buckets have the "Bucket access logging disabled" issue flagged, even though your fix should make them not flag that issue...
What do you think?

**Comment by j4v** [comment] 2019-10-10 16:13
@regevbr are you sure this is caused by the `bugfix/514` branch? There's nothing relating to S3 in there... Could you compare with `develop` to confirm that branch is causing the issue?

**Comment by regevbr** [comment] 2019-10-10 19:37
@j4v my bas I thought those 2 warnings are related, but they have nothing to do with each other.
I consider this bug fixed via your PR.
Thanks for taking care of it :-)

**Comment by j4v** [comment] 2019-10-11 08:26
Closing, fixed in `develop`.

**Closed by j4v** 2019-10-11 08:26 UTC
Labels: bug, component-provider-aws
