### ISSUE TITLE
GKE Reports No Findings

### ISSUE THREAD

**Issue by sharkymcdongles** [nccgroup/ScoutSuite#1317] opened 2021-06-11 16:06 UTC
I am running on Scout Suite 5.10.2.

When I run the tool:
```
scout gcp --update -s credentials.json  --project project --force --no-browser
2021-06-11 18:02:30 RYZEN scout[209] INFO Launching Scout
2021-06-11 18:02:30 RYZEN scout[209] INFO Authenticating to cloud provider
2021-06-11 18:02:31 RYZEN scout[209] INFO Gathering data from APIs
2021-06-11 18:02:31 RYZEN scout[209] INFO Fetching resources for the Cloud SQL service
2021-06-11 18:02:31 RYZEN scout[209] INFO Fetching resources for the Cloud Storage service
2021-06-11 18:02:33 RYZEN scout[209] INFO Fetching resources for the Compute Engine service
2021-06-11 18:02:33 RYZEN scout[209] INFO Fetching resources for the IAM service
2021-06-11 18:02:34 RYZEN scout[209] INFO Fetching resources for the KMS service
2021-06-11 18:02:34 RYZEN scout[209] INFO Fetching resources for the Stackdriver Logging service
2021-06-11 18:02:35 RYZEN scout[209] INFO Fetching resources for the Stackdriver Monitoring service
2021-06-11 18:02:35 RYZEN scout[209] INFO Fetching resources for the Kubernetes Engine service
2021-06-11 18:04:16 RYZEN scout[209] INFO Updating existing data
2021-06-11 18:04:16 RYZEN scout[209] INFO Running pre-processing engine
2021-06-11 18:04:16 RYZEN scout[209] INFO Running rule engine
2021-06-11 18:04:17 RYZEN scout[209] INFO Applying display filters
2021-06-11 18:04:17 RYZEN scout[209] INFO Running post-processing engine
2021-06-11 18:04:17 RYZEN scout[209] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_gcp-project.js
2021-06-11 18:04:17 RYZEN scout[209] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_gcp-project.js
2021-06-11 18:04:17 RYZEN scout[209] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_errors_gcp-project.json
2021-06-11 18:04:18 RYZEN scout[209] INFO Creating scoutsuite-report/gcp-project.html
```

I get a report but there are no findings for GKE as if the rules weren't even run despite this output:

2021-06-11 18:02:35 RYZEN scout[209] INFO Fetching resources for the Kubernetes Engine service

Any idea where I am going wrong?

**Comment by lowSoA** [comment] 2021-06-12 15:44
My guess is that it has to do with the `--update` flag, could you run ScoutSuite without it? Also, you have the `--debug` flag which will print detailed information, including the rules/findings that are being checked. Without specifying any rulesets, by default it will run the [default ruleset](https://github.com/nccgroup/ScoutSuite/blob/master/ScoutSuite/providers/gcp/rules/rulesets/default.json), which does include checks for GKE.

**Comment by sharkymcdongles** [comment] 2021-06-12 18:02
@lowSoA I just ran it as so:
```
scout gcp -s credentials.json  --project project --force --no-browser
2021-06-12 19:48:03 RYZEN scout[92] INFO Launching Scout
2021-06-12 19:48:03 RYZEN scout[92] INFO Authenticating to cloud provider
2021-06-12 19:48:05 RYZEN scout[92] INFO Gathering data from APIs
2021-06-12 19:48:05 RYZEN scout[92] INFO Fetching resources for the Cloud SQL service
2021-06-12 19:48:06 RYZEN scout[92] INFO Fetching resources for the Cloud Storage service
2021-06-12 19:48:06 RYZEN scout[92] INFO Fetching resources for the Compute Engine service
2021-06-12 19:48:06 RYZEN scout[92] INFO Fetching resources for the IAM service
2021-06-12 19:48:06 RYZEN scout[92] INFO Fetching resources for the KMS service
2021-06-12 19:48:07 RYZEN scout[92] INFO Fetching resources for the Stackdriver Logging service
2021-06-12 19:48:07 RYZEN scout[92] INFO Fetching resources for the Stackdriver Monitoring service
2021-06-12 19:48:07 RYZEN scout[92] INFO Fetching resources for the Kubernetes Engine service
2021-06-12 19:49:46 RYZEN scout[92] INFO Running pre-processing engine
2021-06-12 19:49:46 RYZEN scout[92] INFO Running rule engine
2021-06-12 19:49:47 RYZEN scout[92] INFO Applying display filters
2021-06-12 19:49:47 RYZEN scout[92] INFO Running post-processing engine
2021-06-12 19:49:47 RYZEN scout[92] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_results_gcp-project.js
2021-06-12 19:49:47 RYZEN scout[92] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_exceptions_gcp-project.js
2021-06-12 19:49:47 RYZEN scout[92] INFO Saving data to scoutsuite-report/scoutsuite-results/scoutsuite_errors_gcp-project.json
2021-06-12 19:49:47 RYZEN scout[92] INFO Creating scoutsuite-report/gcp-project.html
```

This is what I still see :'(

I also manually added cluster viewer privs to the service account as a test and still get the same result.

With debug on I do see:
```
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Basic Authentication Enabled" (kubernetesengine-basic-authentication-enabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Certificate Authentication Enabled" (kubernetesengine-certificate-authentication-enabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Alias IP Disabled" (kubernetesengine-cluster-alias-ip-disabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Clusters Lacking Labels" (kubernetesengine-cluster-has-no-labels.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Cluster Logging Disabled" (kubernetesengine-cluster-logging-disabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Master Authorized Networks Disabled" (kubernetesengine-cluster-master-authorized-networks-disabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Cluster Monitoring Disabled" (kubernetesengine-cluster-monitoring-disabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Network Policy Disabled" (kubernetesengine-cluster-network-policy-disabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Pod Security Policy Disabled" (kubernetesengine-cluster-pod-security-policy-config-disabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Private Google Access Disabled" (kubernetesengine-cluster-private-google-access-disabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "The GKE Dashboard Enabled" (kubernetesengine-dashboard-enabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Default Service Account in Use" (kubernetesengine-default-service-account-used.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Legacy Authorization (ABAC) Enabled" (kubernetesengine-legacy-abac-enabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Lack of Container-Optimized OS Node Images" (kubernetesengine-node-container-optimized-os-not-used.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Private Cluster Disabled" (kubernetesengine-private-cluster-disabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Lack of Access Scope Limitation" (kubernetesengine-scopes-not-limited.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Legacy Metadata Endpoints Enabled" (kubernetesengine-legacy-metadata-endpoints-enabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Nodes Auto-Repair Disabled" (kubernetesengine-node-auto-repair-disabled.json)
2021-06-12 19:59:13 RYZEN scout[227] DEBUG Processing Kubernetes Engine rule "Nodes Auto-Upgrade Disabled" (kubernetesengine-node-auto-upgrade-disabled.json)
```

But the report still shows no resources. Any idea where I might be going wrong? Is there some IAM permission I'm missing? I added the ones I saw in the guides on here plus extras trying to figure out what's not working:

```
Kubernetes Engine Cluster Viewer
Security Reviewer
Stackdriver Accounts Viewer
Viewer
```

**Comment by sharkymcdongles** [comment] 2021-06-12 18:25
I tried running it again after giving the account owner privs for the project with the same result. :(

**Comment by lowSoA** [comment] 2021-06-14 15:19
The permissions seem fine.

The only other issue might be is the `--project` flag, which should be `--project-id`. As per the [ScoutSuite GCP wiki](https://github.com/nccgroup/ScoutSuite/wiki/Google-Cloud-Platform#execution): "_By default, only the inferred default Project will be scanned_".

**Comment by sharkymcdongles** [comment] 2021-06-15 06:17
@lowSoA  ran it now with the --project-id flag instead with the same result. :'(

**Comment by lowSoA** [comment] 2021-06-15 09:17
I just did a test run and everything seems fine on version 5.10.2 regarding GKE, so the issue is not related to ScoutSuite.

Could you please send the contents of `scoutsuite-report/scoutsuite-results/` to `scoutsuite@nccgroup.com`?

**Comment by sharkymcdongles** [comment] 2021-06-15 11:02
> I just did a test run and everything seems fine on version 5.10.2 regarding GKE, so the issue is not related to ScoutSuite.
> 
> Could you please send the contents of `scoutsuite-report/scoutsuite-results/` to `scoutsuite@nccgroup.com`?

@lowSoA 
I have sent it over now with the ticket title and number in the subject. Thanks!

**Comment by lowSoA** [comment] 2021-06-17 09:11
@sharkymcdongles was able to identify the root cause of this bug. It was caused because in GKE you can have regional or zonal clusters. Currently, ScouSuite is only able to retrieve [zonal clusters](https://github.com/nccgroup/ScoutSuite/blob/b9b8e201a45bd63835f611eec67fe3bb7c892a0a/ScoutSuite/providers/gcp/facade/gke.py#L17). This should be changed for `projects.locations.clusters.list` (using locations "-") in order to cover both cases.

References:
- [projects.locations.clusters.list](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters/list)
- [projects.zones.clusters.list](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters/list)

**Comment by Elgin-Lee** [comment] 2021-06-18 15:24
I am facing the same issue as above. To be exact, to implement the fix mentioned above change line 17 of gke.py to the following line, replacing project-name with your project name. Have verified and confirmed that the fix works.

gke_client.projects().locations().clusters().list(parent="projects/<project-name>/locations/-").execute()

**Comment by x4v13r64** [comment] 2021-08-30 12:16
Closed in `develop`.

**Closed by x4v13r64** 2021-08-30 12:16 UTC
Labels: bug, component-provider-gcp
