### ISSUE TITLE
Docker dependency issue due to lack of virtualenv usage

### ISSUE THREAD

**Issue by munntjlx** [nccgroup/ScoutSuite#736] opened 2020-05-07 21:57 UTC
**Describe the bug**

When building the docker image, one of the required packages fails because its expecting 2.8 but the supplied debian uses 2.9.2

**To Reproduce**

docker build -t scout:latest .

**Additional context**
It seems to work, but oci fails to build. Might want to update your requirement.txt

**Comment by j4v** [comment] 2020-05-08 07:19
Thanks, will look into it.

**Comment by j4v** [comment] 2020-05-18 15:06
Confirmed and raised with OCI - https://github.com/oracle/oci-python-sdk/issues/254.

**Comment by 2mol** [comment] 2020-05-26 06:48
I have the same issue, but when installing via pip. Is there a workaround? I don't see `cryptography` in your `requirements.txt`, so I'm not sure how to force a lower version onto a transitive dependency, but presumably your devs have it somehow installed and it works?

**Comment by j4v** [comment] 2020-05-26 09:15
@2mol while pip complains about the dependency, it should install/run fine.

`cryptography` isn't a dependency of Scout but it comes with most distros.

**Comment by 2mol** [comment] 2020-05-26 09:17
I wish :) But alas, when I do `scout azure --cli`, I get an error:

```
Traceback (most recent call last):
  File "/Users/jurichome/work/cloud-architecture/testing/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/jurichome/work/cloud-architecture/testing/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/jurichome/work/cloud-architecture/testing/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 2.9.2 (/Users/jurichome/work/cloud-architecture/testing/venv/lib/python3.8/site-packages), Requirement.parse('cryptography==2.8'), {'oci'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jurichome/work/cloud-architecture/testing/venv/bin/scout", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/jurichome/work/cloud-architecture/testing/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/Users/jurichome/work/cloud-architecture/testing/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Users/jurichome/work/cloud-architecture/testing/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/jurichome/work/cloud-architecture/testing/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/jurichome/work/cloud-architecture/testing/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/jurichome/work/cloud-architecture/testing/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography==2.8' distribution was not found and is required by oci
```

**Comment by j4v** [comment] 2020-05-26 11:39
Are you using a virtualenv? I can't reproduce your issue.

**Comment by 2mol** [comment] 2020-05-26 11:50
Yeah, my bad, I was using `venv`, assuming that there would be no difference.

With `virtualenv` this problem doesn't arise. Weird that that's the case, but feel free to ignore what I wrote above.

**Comment by j4v** [comment] 2020-05-28 08:37
So the issue is really that we aren't using a virtualenv in https://github.com/nccgroup/ScoutSuite/blob/master/Dockerfile.

**Comment by j4v** [comment] 2020-09-06 09:56
This should be fixed in `develop` via https://github.com/nccgroup/ScoutSuite/pull/775.

**Closed by j4v** 2020-09-06 09:56 UTC
Labels: bug
